# Grupo 4 - Homework 1

1- Use f-string para concaternar textos o valores numéricos. De 2 ejemplos.

In [7]:
#Example_1
a1 = "Chile"
print(a1)

Chile


In [8]:
a2 = "Mundial"
print(a2)

Mundial


In [9]:
a3 = "Qatar 2022"
print(a3)

Qatar 2022


In [18]:
print(f'{a1} no va al {a2} de {a3}')

Chile no va al Mundial de Qatar 2022


In [12]:
#Example_2
b1 = "07 de abril de 2022"
print(b1)

07 de abril de 2022


In [13]:
b2 = "el tipo de cambio del BCR"
print(b2)

el tipo de cambio del BCR


In [19]:
b3 = "S/.3.71"
print(b3)

S/.3.71


In [20]:
print(f'Hoy, {b1}, {b2} cotiza en {b3}')

Hoy, 07 de abril de 2022, el tipo de cambio del BCR cotiza en S/.3.71


# Diccionarios y listas

2- Crear una Lista de 3 distritos de Lima, añadir 2 distritos del Callao. Extraer el primer y último elemento usando el Indexing

In [46]:
Dist_Lima = ["MAGDALENA DEL MAR", "PUEBO LIBRE", "SAN MIGUEL"]
print(Dist_Lima)

['MAGDALENA DEL MAR', 'PUEBO LIBRE', 'SAN MIGUEL']


In [36]:
Dist_Callao = ["VENTANILLA", "LA PUNTA"]
print(Dist_Callao)

['VENTANILLA', 'LA PUNTA']


In [37]:
Dist_Lima.extend(Dist_Callao)
print(Dist_Lima)

['MAGDALENA DEL MAR', 'PUEBO LIBRE', 'SAN MIGUEL', 'VENTANILLA', 'LA PUNTA']


In [38]:
#The first element of the new list "Districts" comes from the list "Dist_Lima"
Dist_Lima[0]

'MAGDALENA DEL MAR'

In [39]:
#The last element of the new list "Districts" comes from the list "Dist_Callao" 
Dist_Callao[-1]

'LA PUNTA'

In [42]:
print([Dist_Lima[i] for i in (0,-1)], '\n')

['MAGDALENA DEL MAR', 'LA PUNTA'] 



3- Crear un diccionario con los 5 distritos del ejercicio a. Incluir información de población proyectada e incidencia de pobreza (limite superior).Use la información del Mapa de Pobreza 2018

In [47]:
Population = {'MAGDALENA DEL MAR' : 65139, 'PUEBO LIBRE' : 94010, 'SAN MIGUEL' : 173309, 'VENTANILLA' : 369618, 'LA PUNTA' : 3935}
print(Population)

{'MAGDALENA DEL MAR': 65139, 'PUEBO LIBRE': 94010, 'SAN MIGUEL': 173309, 'VENTANILLA': 369618, 'LA PUNTA': 3935}


In [48]:
Poverty = {'MAGDALENA DEL MAR' : 1.2, 'PUEBO LIBRE' : 1.2, 'SAN MIGUEL' : 2.1, 'VENTANILLA' : 29.4, 'LA PUNTA' : 3.7}
print(Poverty)

{'MAGDALENA DEL MAR': 1.2, 'PUEBO LIBRE': 1.2, 'SAN MIGUEL': 2.1, 'VENTANILLA': 29.4, 'LA PUNTA': 3.7}


In [66]:
Districts_PP = {'MAGDALENA DEL MAR': {'Population':65139, 'Poverty': 1.2}, 'PUEBO LIBRE':{'Population':94010, 'Poverty': 1.2}, 'SAN MIGUEL' :{'Population':173309, 'Poverty': 2.1}, 'VENTANILLA' :{'Population':369618, 'Poverty': 29.4}, 'LA PUNTA': {'Population':3935, 'Poverty': 3.7}}  
Districts_PP

{'MAGDALENA DEL MAR': {'Population': 65139, 'Poverty': 1.2},
 'PUEBO LIBRE': {'Population': 94010, 'Poverty': 1.2},
 'SAN MIGUEL': {'Population': 173309, 'Poverty': 2.1},
 'VENTANILLA': {'Population': 369618, 'Poverty': 29.4},
 'LA PUNTA': {'Population': 3935, 'Poverty': 3.7}}

4- Muestre la información de pobreza y de población de 3 distritos

In [83]:
A = "PUEBO LIBRE:"
print(A, (Districts_PP.get('PUEBO LIBRE')))

PUEBO LIBRE: {'Population': 94010, 'Poverty': 1.2}


In [184]:
B = "SAN MIGUEL:"
print(B, (Districts_PP.get('SAN MIGUEL')))

SAN MIGUEL: {'Population': 173309, 'Poverty': 2.1}


In [85]:
C = "VENTANILLA:"
print(C, (Districts_PP.get('VENTANILLA')))

VENTANILLA: {'Population': 369618, 'Poverty': 29.4}


# Matrices

5- Crear matrices y dar dos ejemplos de concatenación. Unión vertical y horizontal.

In [102]:
import numpy as np

In [111]:
Q = np.array([[2,5,9],[4,8,6]])
print(Q)

[[2 5 9]
 [4 8 6]]


In [112]:
P = np.array([[1,3,6], [9,7,0]])
print(P)

[[1 3 6]
 [9 7 0]]


In [113]:
R = np.concatenate((Q,P), axis = 0)
print(R)

[[2 5 9]
 [4 8 6]
 [1 3 6]
 [9 7 0]]


In [120]:
S = np.concatenate((Q,P), axis = 1)
print(S)

[[2 5 9 1 3 6]
 [4 8 6 9 7 0]]


6- Crear una matriz de dimensión 4x8, seleccionar las ultimas dos columnas y primeras 3 filas.

In [127]:
MATRIX = np.array([np.arange(16,24), np.arange(24,32), np.arange(32,40), np.arange(40,48)])
print(MATRIX)

[[16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]


In [136]:
MATRIX[:,6:8]

array([[22, 23],
       [30, 31],
       [38, 39],
       [46, 47]])

In [134]:
MATRIX[0:3,:]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

# Operaciones con matrices

7- Obtener el estimador de la varianza del termino de perturbación

In [139]:
import random

In [155]:
random.seed(456)

x1 = np.random.rand(20) # uniform distribution  [0,1]
x2 = np.random.rand(20) # uniform distribution [0,1]
x3 = np.random.rand(20) # uniform distribution [0,1]
x4 = np.random.rand(20) # uniform distribution [0,1]
e = np.random.normal(0,1,20) # normal distribution mean = 0 and sd = 1

# Poblacional regression (Data Generating Process GDP)

Y = 20 + 5*x1 + 9*x2 + 6*x3 + 4*x4 + e

In [156]:
X = np.column_stack((np.ones(20),x1,x2,x3,x4))
X

array([[1.        , 0.97504041, 0.12016147, 0.41453752, 0.47822933],
       [1.        , 0.57964395, 0.23374101, 0.25669446, 0.62151338],
       [1.        , 0.22969502, 0.48037629, 0.6911287 , 0.40444375],
       [1.        , 0.47126395, 0.51029466, 0.32921284, 0.03750686],
       [1.        , 0.07726647, 0.81031918, 0.14934652, 0.53055026],
       [1.        , 0.18757521, 0.32622639, 0.12940466, 0.99041313],
       [1.        , 0.02931691, 0.6292115 , 0.50057782, 0.55785909],
       [1.        , 0.8269459 , 0.48801071, 0.69908513, 0.44939539],
       [1.        , 0.18732904, 0.02865545, 0.65957524, 0.21437189],
       [1.        , 0.92054887, 0.02773256, 0.67055074, 0.86829373],
       [1.        , 0.69680221, 0.79763138, 0.62302352, 0.95608436],
       [1.        , 0.65943963, 0.92754029, 0.12396127, 0.22788732],
       [1.        , 0.09996852, 0.71900492, 0.3330118 , 0.19208082],
       [1.        , 0.97955447, 0.81965729, 0.54527314, 0.26104959],
       [1.        , 0.69300284, 0.

In [158]:
trX=np.transpose(X)
print(trX)

[[1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.         1.         1.         1.         1.
  1.         1.        ]
 [0.97504041 0.57964395 0.22969502 0.47126395 0.07726647 0.18757521
  0.02931691 0.8269459  0.18732904 0.92054887 0.69680221 0.65943963
  0.09996852 0.97955447 0.69300284 0.68597644 0.16256286 0.89003025
  0.06144095 0.82593292]
 [0.12016147 0.23374101 0.48037629 0.51029466 0.81031918 0.32622639
  0.6292115  0.48801071 0.02865545 0.02773256 0.79763138 0.92754029
  0.71900492 0.81965729 0.52016056 0.53481595 0.06199345 0.20569425
  0.2467997  0.83250414]
 [0.41453752 0.25669446 0.6911287  0.32921284 0.14934652 0.12940466
  0.50057782 0.69908513 0.65957524 0.67055074 0.62302352 0.12396127
  0.3330118  0.54527314 0.09009357 0.32905719 0.71471653 0.94616575
  0.39721455 0.08332378]
 [0.47822933 0.62151338 0.40444375 0.03750686 0.53055026 0.99041313
  0.55785909 0.44939539 0.21437189 0.868

In [160]:
X_X = trX @ X
X_X

array([[20.        , 10.23933681,  9.32053117,  8.68595475,  8.79619667],
       [10.23933681,  7.51514832,  4.84565399,  4.65927583,  4.46614564],
       [ 9.32053117,  4.84565399,  6.00100291,  3.39414229,  3.73823826],
       [ 8.68595475,  4.65927583,  3.39414229,  4.98571074,  4.01658275],
       [ 8.79619667,  4.46614564,  3.73823826,  4.01658275,  5.28993276]])

In [162]:
invX_X = np.linalg.inv(X_X)
invX_X

array([[ 0.8271981 , -0.15769133, -0.58830173, -0.58541768, -0.38210961],
       [-0.15769133,  0.45295466, -0.06303515, -0.11513387,  0.01175962],
       [-0.58830173, -0.06303515,  0.80349259,  0.42055979,  0.14432735],
       [-0.58541768, -0.11513387,  0.42055979,  1.07816087, -0.0451842 ],
       [-0.38210961,  0.01175962,  0.14432735, -0.0451842 ,  0.74680481]])

In [163]:
W = invX_X @ trX
W

array([[ 0.17733787,  0.21052332, -0.05076982,  0.24561788,  0.04814322,
         0.15149741, -0.05380156, -0.17127673,  0.31275932, -0.05861522,
        -0.48198749,  0.01788958,  0.12009516, -0.22843704,  0.23034083,
         0.20926852,  0.20691922, -0.18229683,  0.23083048,  0.06596189],
       [ 0.23427985,  0.06788173, -0.15874671, -0.01385911, -0.18472749,
        -0.09654397, -0.23514779,  0.11091218, -0.14806458,  0.19053515,
         0.04716174,  0.07094501, -0.19381485,  0.17462565,  0.11701091,
         0.08150364, -0.16595221,  0.12952793, -0.18472073,  0.15719364],
       [-0.30985532, -0.23937376,  0.13223144, -0.064123  ,  0.19729528,
        -0.14063898,  0.20645428,  0.11055174, -0.26875505, -0.21672056,
         0.4086739 ,  0.20042564,  0.15088576,  0.27553701, -0.1274924 ,
        -0.06249374, -0.19536547, -0.00784795, -0.14789764,  0.09850881],
       [-0.22181304, -0.30517692,  0.31703705, -0.07181702, -0.11647892,
        -0.37504822,  0.19032501,  0.25803118,  

In [185]:
Z_betas = W @ Y
print(Z_betas)

[19.32590636  4.25055417 10.22102975  6.79963583  4.17122226]


In [167]:
#Procedimiento directo
Betas = np.linalg.inv(X_X) @ (trX @ Y )
print(Betas)

[19.32590636  4.25055417 10.22102975  6.79963583  4.17122226]


In [170]:
#Tomando en cuenta el modelo estimado (Y_hat=X*beta)
Y_hat = X @ Betas
print(Y_hat)

[29.5120474  28.51668757 31.59862611 28.93975306 31.16517313 28.46871247
 31.61241008 34.45690902 25.79411106 31.70355149 38.66468935 33.4027673
 30.16536946 36.66385188 29.60700274 29.97268496 27.03606033 33.76531684
 27.09148406 32.92142155]


In [171]:
#Para hallar la SRC (tr_e_hat*e_hat). Primero se halla e_hat (e_hat = Y - Y_hat) y su traspuesta

e_hat = Y - Y_hat
e_hat

array([-0.70097123,  1.19216079, -0.22313953,  0.8430258 ,  0.13045511,
       -0.58627381,  0.83254861,  1.07114695,  1.18740251, -0.07837831,
        0.1051835 ,  0.42565232, -1.48263667, -0.63615412, -0.65120992,
        0.16716462, -1.76966174, -0.19461466,  0.52775655, -0.15945676])

In [173]:
#Sacando la traspuesta de e_hat

tr_e_hat = np.transpose(e_hat)
tr_e_hat

array([-0.70097123,  1.19216079, -0.22313953,  0.8430258 ,  0.13045511,
       -0.58627381,  0.83254861,  1.07114695,  1.18740251, -0.07837831,
        0.1051835 ,  0.42565232, -1.48263667, -0.63615412, -0.65120992,
        0.16716462, -1.76966174, -0.19461466,  0.52775655, -0.15945676])

In [174]:
#Hallando la SRC ((e_hat)'*e_hat)

SRC = tr_e_hat @  e_hat
SRC

13.011084490941068

In [175]:
#Hallando la SD, teniendo en cuenta que se tiene 20 observaciones con k=5 (4 variables explicativas y la constante). Entonces, n-k=20-5=15
SD = SRC/15
SD

0.8674056327294045

8- matriz de varianza y covarianza de los coeficientes

In [176]:
#Para hallar la matriz de varianza y covarianza de los betas, se necesita: V(betas)=SD*[(X'*X)^-1]= SD*invX_X

Varianza_betas = 0.4304781 * invX_X

Varianza_betas

array([[ 0.35609067, -0.06788266, -0.25325101, -0.25200949, -0.16448982],
       [-0.06788266,  0.19498706, -0.02713525, -0.04956261,  0.00506226],
       [-0.25325101, -0.02713525,  0.34588596,  0.18104178,  0.06212976],
       [-0.25200949, -0.04956261,  0.18104178,  0.46412464, -0.01945081],
       [-0.16448982,  0.00506226,  0.06212976, -0.01945081,  0.32148311]])

# Matriz generadora de residuos

\begin{equation}
 M = I - X(X'X)^{-1}X'
\end{equation}

9 - Matriz generador de residuos

In [178]:
#Operando primero las matrices: X(X'X)^{-1} = X*invX_X

G = X @ invX_X
G

array([[ 0.17733787,  0.23427985, -0.30985532, -0.22181304, -0.01488751],
       [ 0.21052332,  0.06788173, -0.23937376, -0.30517692,  0.11099265],
       [-0.05076982, -0.15874671,  0.13223144,  0.31703705, -0.03926461],
       [ 0.24561788, -0.01385911, -0.064123  , -0.07181702, -0.28978317],
       [ 0.04814322, -0.18472749,  0.19729528, -0.11647892,  0.12521961],
       [ 0.15149741, -0.09654397, -0.14063898, -0.37504822,  0.40097783],
       [-0.05380156, -0.23514779,  0.20645428,  0.19032501,  0.10304121],
       [-0.17127673,  0.11091218,  0.11055174,  0.25803118,  0.00207128],
       [ 0.31275932, -0.14806458, -0.26875505,  0.10650773, -0.24547935],
       [-0.05861522,  0.19053515, -0.21672056,  0.00398758,  0.25086589],
       [-0.48198749,  0.04716174,  0.4086739 ,  0.29832814,  0.42706211],
       [ 0.01788958,  0.07094501,  0.20042564, -0.14790208, -0.07589917],
       [ 0.12009516, -0.19381485,  0.15088576,  0.0558184 , -0.14876194],
       [-0.22843704,  0.17462565,  0.2

In [180]:
#Entonces, M ahora es: M = I - G*X'; pero H = G*trX. Entonces, M = I - H

H = G @ trX
H

array([[ 0.26946805,  0.1745199 , -0.07701889,  0.05604592, -0.09666744,
         0.07675155, -0.13009812,  0.05810534,  0.06285239,  0.22274721,
        -0.0589942 ,  0.01353909, -0.09875499,  0.0280175 ,  0.15351691,
         0.09924665,  0.03223516,  0.1046791 ,  0.01901171,  0.09079716],
       [ 0.1745199 ,  0.18456528, -0.05490031,  0.02405721,  0.03510922,
         0.21560347, -0.02894986, -0.01362418,  0.03888674,  0.15811094,
        -0.01712262,  0.02072212, -0.03510951, -0.05661746,  0.14297793,
         0.02936973,  0.02920194, -0.0106263 ,  0.0950903 ,  0.06873546],
       [-0.07701889, -0.05490031,  0.17952077,  0.04479555,  0.07063058,
        -0.0352715 ,  0.16457535,  0.08647615,  0.12397402, -0.01474059,
         0.10406832, -0.0024513 ,  0.12647066,  0.06473537, -0.07667469,
         0.01512082,  0.14385101,  0.11515082,  0.07657189, -0.05488403],
       [ 0.05604592,  0.02405721,  0.04479555,  0.17185302,  0.02811678,
        -0.07419887,  0.00725646,  0.02243101,  

In [181]:
#Solo falta definir una matriz identidad de (20x20)

I = np.eye(20)
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.

In [182]:
#Finalmente, M = I - H
M = I-H
M

array([[ 0.73053195, -0.1745199 ,  0.07701889, -0.05604592,  0.09666744,
        -0.07675155,  0.13009812, -0.05810534, -0.06285239, -0.22274721,
         0.0589942 , -0.01353909,  0.09875499, -0.0280175 , -0.15351691,
        -0.09924665, -0.03223516, -0.1046791 , -0.01901171, -0.09079716],
       [-0.1745199 ,  0.81543472,  0.05490031, -0.02405721, -0.03510922,
        -0.21560347,  0.02894986,  0.01362418, -0.03888674, -0.15811094,
         0.01712262, -0.02072212,  0.03510951,  0.05661746, -0.14297793,
        -0.02936973, -0.02920194,  0.0106263 , -0.0950903 , -0.06873546],
       [ 0.07701889,  0.05490031,  0.82047923, -0.04479555, -0.07063058,
         0.0352715 , -0.16457535, -0.08647615, -0.12397402,  0.01474059,
        -0.10406832,  0.0024513 , -0.12647066, -0.06473537,  0.07667469,
        -0.01512082, -0.14385101, -0.11515082, -0.07657189,  0.05488403],
       [-0.05604592, -0.02405721, -0.04479555,  0.82814698, -0.02811678,
         0.07419887, -0.00725646, -0.02243101, -