## Trabajo Grupal 1

### Grupo 1

##### Pregunta 1

In [50]:
c1="Primer trabajo grupal"
c2="2022-1"
f'{c1}: Laboratorio de R y Python ciclo {c2}'

'Primer trabajo grupal: Laboratorio de R y Python ciclo 2022-1'

In [2]:
d1="25"
d2="30"
print(f'{d1} x {d2} es 750')

25 x 30 es 750


### Diccionarios y listas

##### Pregunta 2

In [3]:
dis1=["Breña","Pueblo libre","San Miguel","La Punta","Bellavista"]

In [4]:
dis1[0]

'Breña'

In [5]:
dis1[-1]

'Bellavista'

##### Pregunta 3

In [55]:
dic1={"Breña":{"Population":"93111","Poverty":"5.4%"},"Pueblo Libre":{"Population": "94010",
"Poverty":"1.2%"},"San Miguel":{"Population":"173309","Poverty":"2.1%"},"La Punta":{"Population":"3935","Poverty":"3.7%"},
"Bellavista":{"Population":"16370","Poverty":"6.3%"}}

##### Pregunta 4

In [56]:
dic1["Breña"]["Poverty"]

'5.4%'

In [8]:
dic1['Breña']['Population']

'93111'

In [9]:
dic1['Pueblo Libre']['Poverty']

'1.2%'

In [10]:
dic1['Pueblo Libre']['Population']

'94010'

In [11]:
dic1['Bellavista']['Poverty']

'6.3%'

In [12]:
dic1['Bellavista']['Population']

'16370'

### Matrices

##### Pregunta 5

In [3]:
import numpy as np

In [4]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
b=np.array([[20,21,22,23],[24,25,26,27]])
print (b)

[[20 21 22 23]
 [24 25 26 27]]


In [6]:
con1 = np.concatenate((a,b), axis = 0)    # Unión de manera vertical
print (con1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [20 21 22 23]
 [24 25 26 27]]


In [7]:
con2 = np.concatenate((a,b), axis = 1)   # Unión de manera horizontal
print (con2)

[[ 1  2  3  4 20 21 22 23]
 [ 5  6  7  8 24 25 26 27]]


##### Pregunta 6

In [8]:
c=np.array([[23,1,76,23,54,6,9,40],[48,58,67,29,45,21,18,28],[28,67,84,14,74,25,25,75],[86,11,22,33,44,55,66,77]])
print (c)

[[23  1 76 23 54  6  9 40]
 [48 58 67 29 45 21 18 28]
 [28 67 84 14 74 25 25 75]
 [86 11 22 33 44 55 66 77]]


In [9]:
print (c[:,6:8])

[[ 9 40]
 [18 28]
 [25 75]
 [66 77]]


In [10]:
print(c[0:3])

[[23  1 76 23 54  6  9 40]
 [48 58 67 29 45 21 18 28]
 [28 67 84 14 74 25 25 75]]


### Operaciones con matrices

##### Pregunta 7

In [18]:
import random

In [23]:
random.seed(23)
x1 = np.random.rand(10)
x2 = np.random.rand(10)
x3 = np.random.rand(10)
e = np.random.normal(0,1,10)

# Poblacional regression (Data Generating Process GDP)

Y = 13 + 5*x1 + 2*x2 + 5*x3 + e

In [25]:
X = np.column_stack((np.ones(10),x1,x2,x3))
X

array([[1.        , 0.95164766, 0.09976372, 0.39014032],
       [1.        , 0.99973862, 0.12401057, 0.08997083],
       [1.        , 0.61391724, 0.01077803, 0.95742026],
       [1.        , 0.99615359, 0.2973944 , 0.12327638],
       [1.        , 0.95723606, 0.10560767, 0.76062479],
       [1.        , 0.60683573, 0.76718379, 0.76006493],
       [1.        , 0.89091593, 0.48735948, 0.04995963],
       [1.        , 0.31942528, 0.90276231, 0.8826685 ],
       [1.        , 0.13218716, 0.74759943, 0.15461557],
       [1.        , 0.33380658, 0.18317666, 0.31647731]])

In [32]:
(X.T)    # X_transp

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.95164766, 0.99973862, 0.61391724, 0.99615359, 0.95723606,
        0.60683573, 0.89091593, 0.31942528, 0.13218716, 0.33380658],
       [0.09976372, 0.12401057, 0.01077803, 0.2973944 , 0.10560767,
        0.76718379, 0.48735948, 0.90276231, 0.74759943, 0.18317666],
       [0.39014032, 0.08997083, 0.95742026, 0.12327638, 0.76062479,
        0.76006493, 0.04995963, 0.8826685 , 0.15461557, 0.31647731]])

In [33]:
X1=(X.T)@X    # X_transp*X
X1

array([[10.        ,  6.80186384,  3.72563604,  4.48521853],
       [ 6.80186384,  5.58354137,  1.97096142,  2.81367134],
       [ 3.72563604,  1.97096142,  2.3585726 ,  1.75524722],
       [ 4.48521853,  2.81367134,  1.75524722,  3.15406712]])

In [30]:
invX1=np.linalg.inv(X1)    # Inversa de X_transp*X
invX1

array([[ 1.95152767, -1.61167262, -1.26405414, -0.63396987],
       [-1.61167262,  1.66944221,  0.94468854,  0.27687434],
       [-1.26405414,  0.94468854,  1.57156388,  0.08022431],
       [-0.63396987,  0.27687434,  0.08022431,  0.92694492]])

In [34]:
w=invX1@(X.T)
w

array([[ 4.43392497e-02,  1.26481456e-01,  3.41494461e-01,
        -1.08021912e-01, -2.06930472e-01, -4.78112953e-01,
        -1.32058801e-01, -2.64006965e-01,  6.95457484e-01,
         9.81358453e-01],
       [ 1.79313644e-01,  1.99395203e-01, -3.11506280e-01,
         3.66425371e-01,  2.96741501e-01,  3.36596763e-01,
         3.49895493e-01,  1.88068895e-02, -6.41936102e-01,
        -7.93732481e-01],
       [-1.76959709e-01, -1.17504152e-01, -5.90346822e-01,
         1.54264790e-01, -1.32774419e-01,  5.75870627e-01,
         3.47508463e-01,  5.27263366e-01,  4.81257477e-02,
        -6.35447892e-01],
       [-8.40987709e-04, -2.63821231e-01,  4.24348575e-01,
        -2.20031824e-01,  3.44593823e-01,  3.00132493e-01,
        -3.01890205e-01,  3.45079361e-01, -3.94074869e-01,
        -2.33495135e-01]])

In [36]:
beta = np.linalg.inv(X.T @ X) @ ((X.T) @ Y )
beta

array([15.64954932,  2.63559195,  0.82557614,  4.15885883])

In [37]:
Y1=X@beta
Y1

array([19.86260528, 18.76100851, 21.25825845, 19.03321448, 21.42295125,
       21.04329207, 18.60776758, 20.90761672, 17.25816532, 17.99673799])

In [38]:
e1=Y-Y1
e1

array([-1.5594048 , -0.90485379,  0.50052535,  2.30133927,  0.61528198,
       -0.06115663, -0.65441486, -0.52955406,  0.53752063, -0.24528309])

In [40]:
SRC=(e1.T)@e1
SRC

10.23728234417426

In [43]:
Ve=SRC/6
Ve

1.7062137240290431

##### Pregunta 8

In [46]:
Varcov=Ve*invX1
Varcov

array([[ 3.3297233 , -2.74985794, -2.15674652, -1.08168809],
       [-2.74985794,  2.84842521,  1.61184054,  0.4724068 ],
       [-2.15674652,  1.61184054,  2.68142387,  0.13687981],
       [-1.08168809,  0.4724068 ,  0.13687981,  1.58156615]])

##### Pregunta 9

In [47]:
m=X@invX1     # invX1 --> (X'X)^(-1)
m

array([[ 4.43392497e-02,  1.79313644e-01, -1.76959709e-01,
        -8.40987709e-04],
       [ 1.26481456e-01,  1.99395203e-01, -1.17504152e-01,
        -2.63821231e-01],
       [ 3.41494461e-01, -3.11506280e-01, -5.90346822e-01,
         4.24348575e-01],
       [-1.08021912e-01,  3.66425371e-01,  1.54264790e-01,
        -2.20031824e-01],
       [-2.06930472e-01,  2.96741501e-01, -1.32774419e-01,
         3.44593823e-01],
       [-4.78112953e-01,  3.36596763e-01,  5.75870627e-01,
         3.00132493e-01],
       [-1.32058801e-01,  3.49895493e-01,  3.47508463e-01,
        -3.01890205e-01],
       [-2.64006965e-01,  1.88068895e-02,  5.27263366e-01,
         3.45079361e-01],
       [ 6.95457484e-01, -6.41936102e-01,  4.81257477e-02,
        -3.94074869e-01],
       [ 9.81358453e-01, -7.93732481e-01, -6.35447892e-01,
        -2.33495135e-01]])

In [48]:
n=m@(X.T)    # X(X'X)^(-1)X_transp
n

array([[ 0.1970004 ,  0.20158549,  0.15171053,  0.17023268,  0.19665676,
         0.01675335,  0.11780762, -0.05887831, -0.0643828 ,  0.07151428],
       [ 0.20158549,  0.28751657, -0.00496065,  0.2576417 ,  0.10427143,
        -0.04318696,  0.23367864, -0.14877168,  0.02420203,  0.08802344],
       [ 0.15171053, -0.00496065,  0.55017253, -0.09206732,  0.30373431,
         0.02208928, -0.20254227,  0.08360774, -0.07541472,  0.26367055],
       [ 0.17023268,  0.2576417 , -0.09206732,  0.27574679,  0.09166355,
         0.06544906,  0.28262199, -0.04592711,  0.02172274, -0.02708408],
       [ 0.19665676,  0.10427143,  0.30373431,  0.09166355,  0.3252058 ,
         0.13319417,  0.00994817,  0.07215464, -0.21368757, -0.02314125],
       [ 0.01675335, -0.04318696,  0.02208928,  0.06544906,  0.13319417,
         0.39606478,  0.11741698,  0.41419635,  0.04330653, -0.16528356],
       [ 0.11780762,  0.23367864, -0.20254227,  0.28262199,  0.00994817,
         0.11741698,  0.33394789,  0.02695523

In [49]:
M=np.eye(10)-n     # M = I-X(X'X)^(-1)X_transp
M

array([[ 0.8029996 , -0.20158549, -0.15171053, -0.17023268, -0.19665676,
        -0.01675335, -0.11780762,  0.05887831,  0.0643828 , -0.07151428],
       [-0.20158549,  0.71248343,  0.00496065, -0.2576417 , -0.10427143,
         0.04318696, -0.23367864,  0.14877168, -0.02420203, -0.08802344],
       [-0.15171053,  0.00496065,  0.44982747,  0.09206732, -0.30373431,
        -0.02208928,  0.20254227, -0.08360774,  0.07541472, -0.26367055],
       [-0.17023268, -0.2576417 ,  0.09206732,  0.72425321, -0.09166355,
        -0.06544906, -0.28262199,  0.04592711, -0.02172274,  0.02708408],
       [-0.19665676, -0.10427143, -0.30373431, -0.09166355,  0.6747942 ,
        -0.13319417, -0.00994817, -0.07215464,  0.21368757,  0.02314125],
       [-0.01675335,  0.04318696, -0.02208928, -0.06544906, -0.13319417,
         0.60393522, -0.11741698, -0.41419635, -0.04330653,  0.16528356],
       [-0.11780762, -0.23367864,  0.20254227, -0.28262199, -0.00994817,
        -0.11741698,  0.66605211, -0.02695523