## Grupo 1

##### Pregunta 1

In [7]:
a <- "Primer trabajo grupal"

In [8]:
b <- "2022-1"

In [7]:
# install.packages("devtools")
library(glue)

also installing the dependencies 'glue', 'cli', 'rcmdcheck', 'sessioninfo'




  There are binary versions available but the source versions are later:
            binary source needs_compilation
glue         1.4.2  1.6.2              TRUE
cli          2.5.0  3.2.0              TRUE
rcmdcheck    1.3.3  1.4.0             FALSE
sessioninfo  1.1.1  1.2.2             FALSE
devtools     2.4.1  2.4.3             FALSE

  Binaries will be installed
package 'glue' successfully unpacked and MD5 sums checked
package 'cli' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\PERSONAL\AppData\Local\Temp\RtmpmEWkMc\downloaded_packages


installing the source packages 'rcmdcheck', 'sessioninfo', 'devtools'

Warning message in install.packages("devtools"):
"installation of package 'sessioninfo' had non-zero exit status"Warning message in install.packages("devtools"):
"installation of package 'rcmdcheck' had non-zero exit status"Warning message in install.packages("devtools"):
"installation of package 'devtools' had non-zero exit status"Warning message:
"package 'glue' was built under R version 3.6.3"

In [10]:
c <- glue('{a}: Ciclo {b}')
c

Primer trabajo grupal: Ciclo 2022-1

In [11]:
d <- "25"

In [12]:
e <- "30"

In [13]:
f <- glue('{d} x {e} es igual a 750')
f

25 x 30 es igual a 750

### Diccionarios y listas

##### Pregunta 2

In [1]:
dis1 <- list('Breña', 'Pueblo Libre','San Miguel', 'La Punta', 'Bellavista')
dis1

[[1]]
[1] "Breña"

[[2]]
[1] "Pueblo Libre"

[[3]]
[1] "San Miguel"

[[4]]
[1] "La Punta"

[[5]]
[1] "Bellavista"

##### Pregunta 3

In [14]:
dic1 <- list('Breña'=list('Population'="93111",'Poverty'="5.4%"),"Pueblo_Libre"=list("Population"="94010","Poverty"="1.2%"),
"San_Miguel"=list("Population"="173309","Poverty"="2.1%"),"La_Punta"=list("Population"="3935","Poverty"="3.7%"),"Bellavista"=list("Population"="16370",
"Poverty"="6.3%"))
dic1

$Breña
$Breña$Population
[1] "93111"

$Breña$Poverty
[1] "5.4%"


$Pueblo_Libre
$Pueblo_Libre$Population
[1] "94010"

$Pueblo_Libre$Poverty
[1] "1.2%"


$San_Miguel
$San_Miguel$Population
[1] "173309"

$San_Miguel$Poverty
[1] "2.1%"


$La_Punta
$La_Punta$Population
[1] "3935"

$La_Punta$Poverty
[1] "3.7%"


$Bellavista
$Bellavista$Population
[1] "16370"

$Bellavista$Poverty
[1] "6.3%"

##### Pregunta 4

In [15]:
dic1$Breña$Poverty

[1] "5.4%"

In [16]:
dic1$Breña$Population

[1] "93111"

In [17]:
dic1$Pueblo_Libre$Poverty

[1] "1.2%"

In [18]:
dic1$Pueblo_Libre$Population

[1] "94010"

In [19]:
dic1$Bellavista$Poverty

[1] "6.3%"

In [20]:
dic1$Bellavista$Population

[1] "16370"

### Matrices

##### Pregunta 5

In [21]:
f <- c(1,2,3,4,5,6,7,8,9,10)

In [22]:
m1 <- matrix(f, nrow=2, byrow=TRUE)
print(m1)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    3    4    5
[2,]    6    7    8    9   10


In [23]:
m2 <- matrix(f, nrow=2, byrow=FALSE)
print(m2)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


##### Pregunta 6

In [24]:
e <- matrix(seq(1,32,1),4,8)
e

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    5     9   13   17   21   25   29  
[2,] 2    6    10   14   18   22   26   30  
[3,] 3    7    11   15   19   23   27   31  
[4,] 4    8    12   16   20   24   28   32

In [25]:
e[,c(-1:-6)]

[,1] [,2]
[1,] 25   29  
[2,] 26   30  
[3,] 27   31  
[4,] 28   32

In [26]:
e[c(1:3),]

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    5     9   13   17   21   25   29  
[2,] 2    6    10   14   18   22   26   30  
[3,] 3    7    11   15   19   23   27   31

### Operaciones con matrices

In [2]:
set.seed(23)

x1 <- runif(10)
x2 <- runif(10)
x3 <- runif(10)

e <- rnorm(10)

# Poblacional regression (Data Generating Process GDP)

Y <- 13 + 5*x1 + 2*x2 + 5*x3 + e

In [13]:
X <- cbind(matrix(1,10), x1,x2,x3)
X

x1        x2        x3       
 [1,] 1 0.5766037 0.8659590 0.5863978
 [2,] 1 0.2230729 0.7014217 0.2747410
 [3,] 1 0.3318966 0.3904731 0.1476570
 [4,] 1 0.7107246 0.3147697 0.8014103
 [5,] 1 0.8194490 0.8459473 0.3864098
 [6,] 1 0.4237206 0.1392785 0.8204507
 [7,] 1 0.9635445 0.5181206 0.6849373
 [8,] 1 0.9781304 0.5935508 0.8833893
 [9,] 1 0.8405219 0.9424617 0.1119208
[10,] 1 0.9966112 0.6280196 0.7788340

In [19]:
# install.packages("matlib")

ERROR: Error in library("matlib"): there is no package called 'matlib'


In [21]:
X1 <- t(X) %*% X
X1

x1       x2       x3      
   10.000000 6.864275 5.940002 5.476148
x1  6.864275 5.433422 4.259174 4.076584
x2  5.940002 4.259174 4.131846 2.925396
x3  5.476148 4.076584 2.925396 3.774482

In [22]:
invX1 <- solve(X1)
invX1

x1         x2        x3       
    1.9755819  0.2599059 -1.950019 -1.635597
x1  0.2599059  2.6517912 -1.800311 -1.845793
x2 -1.9500187 -1.8003107  3.371575  2.160434
x3 -1.6355966 -1.8457928  2.160434  2.957008

In [24]:
r <- t(X) %*% Y
r

[,1]    
   202.9841
x1 144.9244
x2 120.9012
x3 116.7387

In [25]:
beta <- invX1 %*% r
beta

[,1]     
   11.981350
x1  3.930930
x2  3.101858
x3  6.895823

In [26]:
Y1 <- X %*% beta
Y1

[,1]    
 [1,] 20.97772
 [2,] 16.92851
 [3,] 15.51542
 [4,] 21.27791
 [5,] 20.49117
 [6,] 19.73667
 [7,] 22.09932
 [8,] 23.75912
 [9,] 18.98055
[10,] 23.21769

In [27]:
e1 <- Y - Y1
e1

[,1]      
 [1,] -0.1226539
 [2,] -0.5567752
 [3,]  0.2209795
 [4,] -0.6870121
 [5,]  1.5245975
 [6,]  0.5981339
 [7,] -0.3866837
 [8,]  0.5240007
 [9,] -0.4993439
[10,] -0.6152428

In [28]:
SRC <- t(e1) %*% e1
SRC

[,1]    
[1,] 4.579991

In [29]:
SD <- SRC/6
SD

[,1]     
[1,] 0.7633318