TAREA GRUPAL 1 /Grupo 5
1. Use f-string para concatenar textos o valores numéricos. De dos ejemplos 

In [29]:
x1 = "Este es nuestro primer trabajo grupal"
x2 = "Jupyter notebooks"
print (f'{x1} del ciclo 2022-1 en {x2}')

Este es nuestro primer trabajo grupal del ciclo 2022-1 en Jupyter notebooks


In [32]:
y1 = 101
y2 = 10
y3= y1+y2
print(f'{y1} + {y2} es {y3}')

101 + 10 es 111


DICCIONAIRO Y LISTAS
2. Crear una lista de tres distritos de Lima y dos distritos del callao. Extraer el primer y último elemento usando el indexing

In [43]:
lista = ["Los Olivos", "Ancón", "Ventanilla", "Santiago de Surco", "Mi Perú"]
print(lista)

['Los Olivos', 'Ancón', 'Ventanilla', 'Santiago de Surco', 'Mi Perú']


2.1 Extrar el primero

In [41]:
lista[0]

'Los Olivos'

2.2 extraer el último

In [44]:
lista[-1]

'Mi Perú'

3. Crear un diccionario con los 5 distritos del ejercicio a. Incluir información de población proyectada e incidencia de pobreza (limite superior).Use la información del Mapa de Pobreza 2018

In [45]:
diccionario ={"Los Olivos":{"población":351983, "pobreza":9.5}, "Ancón":{"población":82677,"pobreza":25.5, 
"Ventanilla":{"población":369618, "pobreza":29.4}, "Santiago de Surco":{"población":408086, "pobreza":1.6}, 
"Mi Perú":{"población":52348,"pobreza":31.0 }}}
print(diccionario)

{'Los Olivos': {'población': 351983, 'pobreza': 9.5}, 'Ancón': {'población': 82677, 'pobreza': 25.5, 'Ventanilla': {'población': 369618, 'pobreza': 29.4}, 'Santiago de Surco': {'población': 408086, 'pobreza': 1.6}, 'Mi Perú': {'población': 52348, 'pobreza': 31.0}}}


4. Muestre la información de pobreza y población de 3 distritos

In [46]:
diccionario["Los Olivos"]["población"] , diccionario["Los Olivos"]["pobreza"]

(351983, 9.5)

In [47]:
diccionario["Ancón"]["población"] , diccionario["Ancón"]["pobreza"]

(82677, 25.5)

In [67]:
diccionario['Mi Perú']['población'] , diccionario['Mi Perú']['pobreza']

<class 'KeyError'>: 'Mi Perú'

MATRICES 
5. crear matrices y dar dos ejemplos de concatenación, union vertical y horizontal

In [10]:
import numpy as np


In [24]:
matriz_1 = np.arange(5,11).reshape(3,2)
print(matriz_1)

[[ 5  6]
 [ 7  8]
 [ 9 10]]


In [26]:
matriz_2 = np.arange(1,7).reshape(3,2)
print(matriz_2)

[[1 2]
 [3 4]
 [5 6]]


5.1 Concatenación horizontal.

In [27]:
matriz_3 =np.concatenate((matriz_1, matriz_2), 1)
print(matriz_3)

[[ 5  6  1  2]
 [ 7  8  3  4]
 [ 9 10  5  6]]


5.2 Concatenación vertical 

In [28]:
matriz_4 =np.concatenate((matriz_1, matriz_2), 0)
print(matriz_4)

[[ 5  6]
 [ 7  8]
 [ 9 10]
 [ 1  2]
 [ 3  4]
 [ 5  6]]


6. Crea una matriz de dimensión 4x8, seleccionar las 2 últimas columnas y las 3 primers filas 

In [58]:
matriz_4x8 = np.arange(1,33).reshape(4,8)
print(matriz_4x8)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]


6.1 Seleccionamos las 2 últimás columnas 

In [62]:
matriz_4x8[:,6:8]

array([[ 7,  8],
       [15, 16],
       [23, 24],
       [31, 32]])

6.2 Seleccionamos las 3 primeras filas

In [66]:
matriz_4x8[0:3,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])