## Grupo 1

##### Pregunta 1

In [67]:
a <- "Primer trabajo grupal"

In [68]:
b <- "2022-1"

In [69]:
# install.packages("devtools")
library(glue)

In [70]:
c <- glue('{a}: Ciclo {b}')
c

Primer trabajo grupal: Ciclo 2022-1

In [71]:
d <- "25"

In [72]:
e <- "30"

In [73]:
f <- glue('{d} x {e} es igual a 750')
f

25 x 30 es igual a 750

### Diccionarios y listas

##### Pregunta 2

In [74]:
dis1 <- list('Breña', 'Pueblo Libre','San Miguel', 'La Punta', 'Bellavista')
dis1

[[1]]
[1] "Breña"

[[2]]
[1] "Pueblo Libre"

[[3]]
[1] "San Miguel"

[[4]]
[1] "La Punta"

[[5]]
[1] "Bellavista"

##### Pregunta 3

In [75]:
dic1 <- list('Breña'=list('Population'="93111",'Poverty'="5.4%"),"Pueblo_Libre"=list("Population"="94010","Poverty"="1.2%"),
"San_Miguel"=list("Population"="173309","Poverty"="2.1%"),"La_Punta"=list("Population"="3935","Poverty"="3.7%"),"Bellavista"=list("Population"="16370",
"Poverty"="6.3%"))
dic1

$Breña
$Breña$Population
[1] "93111"

$Breña$Poverty
[1] "5.4%"


$Pueblo_Libre
$Pueblo_Libre$Population
[1] "94010"

$Pueblo_Libre$Poverty
[1] "1.2%"


$San_Miguel
$San_Miguel$Population
[1] "173309"

$San_Miguel$Poverty
[1] "2.1%"


$La_Punta
$La_Punta$Population
[1] "3935"

$La_Punta$Poverty
[1] "3.7%"


$Bellavista
$Bellavista$Population
[1] "16370"

$Bellavista$Poverty
[1] "6.3%"

##### Pregunta 4

In [76]:
dic1$Breña$Poverty

[1] "5.4%"

In [77]:
dic1$Breña$Population

[1] "93111"

In [78]:
dic1$Pueblo_Libre$Poverty

[1] "1.2%"

In [79]:
dic1$Pueblo_Libre$Population

[1] "94010"

In [80]:
dic1$Bellavista$Poverty

[1] "6.3%"

In [81]:
dic1$Bellavista$Population

[1] "16370"

### Matrices

##### Pregunta 5

In [82]:
f <- c(1,2,3,4,5,6,7,8,9,10)

In [83]:
m1 <- matrix(f, nrow=2, byrow=TRUE)
print(m1)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    3    4    5
[2,]    6    7    8    9   10


In [84]:
m2 <- matrix(f, nrow=2, byrow=FALSE)
print(m2)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


##### Pregunta 6

In [85]:
e <- matrix(seq(1,32,1),4,8)
e

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    5     9   13   17   21   25   29  
[2,] 2    6    10   14   18   22   26   30  
[3,] 3    7    11   15   19   23   27   31  
[4,] 4    8    12   16   20   24   28   32

In [86]:
e[,c(-1:-6)]

[,1] [,2]
[1,] 25   29  
[2,] 26   30  
[3,] 27   31  
[4,] 28   32

In [87]:
e[c(1:3),]

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    5     9   13   17   21   25   29  
[2,] 2    6    10   14   18   22   26   30  
[3,] 3    7    11   15   19   23   27   31

### Operaciones con matrices

##### Pregunta 7

In [43]:
set.seed(23)

x1 <- runif(10)
x2 <- runif(10)
x3 <- runif(10)

e <- rnorm(10)

# Poblacional regression (Data Generating Process GDP)

Y <- 13 + 5*x1 + 2*x2 + 5*x3 + e

In [44]:
X <- cbind(matrix(1,10), x1,x2,x3)
X

x1        x2        x3       
 [1,] 1 0.5766037 0.8659590 0.5863978
 [2,] 1 0.2230729 0.7014217 0.2747410
 [3,] 1 0.3318966 0.3904731 0.1476570
 [4,] 1 0.7107246 0.3147697 0.8014103
 [5,] 1 0.8194490 0.8459473 0.3864098
 [6,] 1 0.4237206 0.1392785 0.8204507
 [7,] 1 0.9635445 0.5181206 0.6849373
 [8,] 1 0.9781304 0.5935508 0.8833893
 [9,] 1 0.8405219 0.9424617 0.1119208
[10,] 1 0.9966112 0.6280196 0.7788340

In [45]:
# install.packages("matlib")

In [46]:
X1 <- t(X) %*% X
X1

x1       x2       x3      
   10.000000 6.864275 5.940002 5.476148
x1  6.864275 5.433422 4.259174 4.076584
x2  5.940002 4.259174 4.131846 2.925396
x3  5.476148 4.076584 2.925396 3.774482

In [47]:
invX1 <- solve(X1)
invX1

x1         x2        x3       
    1.9755819  0.2599059 -1.950019 -1.635597
x1  0.2599059  2.6517912 -1.800311 -1.845793
x2 -1.9500187 -1.8003107  3.371575  2.160434
x3 -1.6355966 -1.8457928  2.160434  2.957008

In [48]:
r <- t(X) %*% Y
r

[,1]    
   202.9841
x1 144.9244
x2 120.9012
x3 116.7387

In [49]:
beta <- invX1 %*% r
beta

[,1]     
   11.981350
x1  3.930930
x2  3.101858
x3  6.895823

In [50]:
Y1 <- X %*% beta
Y1

[,1]    
 [1,] 20.97772
 [2,] 16.92851
 [3,] 15.51542
 [4,] 21.27791
 [5,] 20.49117
 [6,] 19.73667
 [7,] 22.09932
 [8,] 23.75912
 [9,] 18.98055
[10,] 23.21769

In [51]:
e1 <- Y - Y1
e1

[,1]      
 [1,] -0.1226539
 [2,] -0.5567752
 [3,]  0.2209795
 [4,] -0.6870121
 [5,]  1.5245975
 [6,]  0.5981339
 [7,] -0.3866837
 [8,]  0.5240007
 [9,] -0.4993439
[10,] -0.6152428

In [52]:
SRC <- t(e1) %*% e1
SRC

[,1]    
[1,] 4.579991

In [53]:
SD <- SRC/6
SD

[,1]     
[1,] 0.7633318

##### Pregunta 8

In [61]:
Varcov <- 0.7633318 * invX1
Varcov

x1         x2        x3       
    1.5080245  0.1983944 -1.488511 -1.248503
x1  0.1983944  2.0241966 -1.374234 -1.408952
x2 -1.4885113 -1.3742344  2.573630  1.649128
x3 -1.2485029 -1.4089523  1.649128  2.257178

##### Pregunta 9

In [62]:
m <- X %*% invX1
m

x1          x2          x3        
 [1,] -0.52230207 -0.85242580  1.19843472  0.9049429
 [2,]  0.21640897 -0.91844338  0.60683605  0.2804437
 [3,]  1.05890673  0.16450935 -0.91202358 -0.9679948
 [4,]  0.23571254  0.09867834 -0.43688013  0.1023691
 [5,] -0.09306219  0.19671299  0.26170577 -0.1778993
 [6,]  0.47218727 -0.38160222 -0.47072995  0.3092843
 [7,]  0.09538686  0.61799456 -0.45805441 -0.2693699
 [8,] -0.37250001  0.15457406  0.19874767  0.4534939
 [9,]  0.17316323  0.58548796 -0.04384200 -0.8199489
[10,] -0.26390132  0.33451414  0.05580585  0.1846790

In [63]:
n <- m %*% t(X)
n

[,1]         [,2]        [,3]        [,4]        [,5]        [,6]       
 [1,]  0.554638028  0.37677788 -0.20364169 -0.02568047  0.14266994  0.02588485
 [2,]  0.376777880  0.51422652  0.18994334 -0.02058723  0.08550901  0.14185505
 [3,] -0.203641687  0.18994334  0.61445500  0.11298913  0.04814716  0.20739542
 [4,] -0.025680465 -0.02058723  0.11298913  0.25036866 -0.01344674  0.30066534
 [5,]  0.142669941  0.08550901  0.04814716 -0.01344674  0.22078130 -0.11921848
 [6,]  0.025884845  0.14185505  0.20739542  0.30066534 -0.11921848  0.49868455
 [7,] -0.102889471 -0.16205157  0.08186490  0.17455333  0.11022481  0.07244204
 [8,]  0.154663130 -0.07401945 -0.17663026  0.16335400  0.09753009  0.09274685
 [9,] -0.008023869  0.04774443  0.22929441 -0.08163172  0.29901641 -0.25758735
[10,]  0.085601668 -0.09939799 -0.10381741  0.13941570  0.12878651  0.03713172
      [,7]        [,8]         [,9]         [,10]      
 [1,] -0.10288947  0.154663130 -0.008023869  0.08560167
 [2,] -0.16205157 -0.074019452  0.047744431 -0.09939799
 [3,]  0.08186490 -0.176630261  0.229294410 -0.10381741
 [4,]  0.17455333  0.163354000 -0.081631718  0.13941570
 [5,]  0.11022481  0.097530093  0.299016411  0.12878651
 [6,]  0.07244204  0.092746854 -0.257587345  0.03713172
 [7,]  0.26902327  0.190029110  0.152977983  0.21382561
 [8,]  0.19002911  0.297272059 -0.004509671  0.25956414
 [9,]  0.15297798 -0.004509671  0.532189953  0.09052942
[10,]  0.21382561  0.259564139  0.090529416  0.24836064

In [66]:
M <- diag(10)-n
M

[,1]         [,2]        [,3]        [,4]        [,5]        [,6]       
 [1,]  0.445361972 -0.37677788  0.20364169  0.02568047 -0.14266994 -0.02588485
 [2,] -0.376777880  0.48577348 -0.18994334  0.02058723 -0.08550901 -0.14185505
 [3,]  0.203641687 -0.18994334  0.38554500 -0.11298913 -0.04814716 -0.20739542
 [4,]  0.025680465  0.02058723 -0.11298913  0.74963134  0.01344674 -0.30066534
 [5,] -0.142669941 -0.08550901 -0.04814716  0.01344674  0.77921870  0.11921848
 [6,] -0.025884845 -0.14185505 -0.20739542 -0.30066534  0.11921848  0.50131545
 [7,]  0.102889471  0.16205157 -0.08186490 -0.17455333 -0.11022481 -0.07244204
 [8,] -0.154663130  0.07401945  0.17663026 -0.16335400 -0.09753009 -0.09274685
 [9,]  0.008023869 -0.04774443 -0.22929441  0.08163172 -0.29901641  0.25758735
[10,] -0.085601668  0.09939799  0.10381741 -0.13941570 -0.12878651 -0.03713172
      [,7]        [,8]         [,9]         [,10]      
 [1,]  0.10288947 -0.154663130  0.008023869 -0.08560167
 [2,]  0.16205157  0.074019452 -0.047744431  0.09939799
 [3,] -0.08186490  0.176630261 -0.229294410  0.10381741
 [4,] -0.17455333 -0.163354000  0.081631718 -0.13941570
 [5,] -0.11022481 -0.097530093 -0.299016411 -0.12878651
 [6,] -0.07244204 -0.092746854  0.257587345 -0.03713172
 [7,]  0.73097673 -0.190029110 -0.152977983 -0.21382561
 [8,] -0.19002911  0.702727941  0.004509671 -0.25956414
 [9,] -0.15297798  0.004509671  0.467810047 -0.09052942
[10,] -0.21382561 -0.259564139 -0.090529416  0.75163936