### Pregunta 1

In [1]:
library(glue)

In [2]:
year <- 2020
poverty_rate <- "30.1 %"
glue('En {year}, la tasa de pobreza a nivel nacional fue {poverty_rate}.')

En 2020, la tasa de pobreza a nivel nacional fue 30.1 %.

In [3]:
name <- "Juan"
age <- 20
glue('{name} el próximo año tendra {age+1} años.')

Juan el próximo año tendra 21 años.

# Diccionarios y Listas

### Pregunta 2

In [4]:
distritos <- list('Breña','Surco','Chorrillos','Bellavista','La Perla')
cat("Distritos")
print(distritos)
cat("\n","Primer y último distrito")
print(distritos[c(1,length(distritos))])

Distritos[[1]]
[1] "Breña"

[[2]]
[1] "Surco"

[[3]]
[1] "Chorrillos"

[[4]]
[1] "Bellavista"

[[5]]
[1] "La Perla"


 Primer y último distrito[[1]]
[1] "Breña"

[[2]]
[1] "La Perla"



### Pregunta 3

In [5]:
diccionario <- list(Breña = list(Poverty_Rate = "5.4 %", Population = "93.1 mil"),
                    Surco = list(Poverty_Rate = "1.6 %", Population = "408 mil"),
                    Chorrillos = list(Poverty_Rate = "14.3 %", Population = "355.9 mil"),
                    Bellavista = list(Poverty_Rate = "6.3 %", Population = "80.7 mil"),
                    La_Perla = list(Poverty_Rate = "4.7 %", Population = "64.5 mil"))
diccionario

$Breña
$Breña$Poverty_Rate
[1] "5.4 %"

$Breña$Population
[1] "93.1 mil"


$Surco
$Surco$Poverty_Rate
[1] "1.6 %"

$Surco$Population
[1] "408 mil"


$Chorrillos
$Chorrillos$Poverty_Rate
[1] "14.3 %"

$Chorrillos$Population
[1] "355.9 mil"


$Bellavista
$Bellavista$Poverty_Rate
[1] "6.3 %"

$Bellavista$Population
[1] "80.7 mil"


$La_Perla
$La_Perla$Poverty_Rate
[1] "4.7 %"

$La_Perla$Population
[1] "64.5 mil"

### Pregunta 4

In [6]:
print(diccionario$Surco)

$Poverty_Rate
[1] "1.6 %"

$Population
[1] "408 mil"



In [7]:
print(diccionario$Bellavista)

$Poverty_Rate
[1] "6.3 %"

$Population
[1] "80.7 mil"



In [8]:
print(diccionario$La_Perla)

$Poverty_Rate
[1] "4.7 %"

$Population
[1] "64.5 mil"



# Matrices

### Pregunta 5

In [9]:
M <- matrix(1:9,nrow=3,byrow=T)
N <- matrix(10:15,nrow=2)
O <- matrix(6:9,nrow=2)
cat("Matriz M\n")
print(M)
cat("\nMatriz N\n")
print(N)
cat("\nMatriz O\n")
print(O)


Matriz M
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

Matriz N
     [,1] [,2] [,3]
[1,]   10   12   14
[2,]   11   13   15

Matriz O
     [,1] [,2]
[1,]    6    8
[2,]    7    9


In [10]:
P <- rbind(M,N)
P

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   12   14  
[5,] 11   13   15

In [11]:
R <- cbind(O,N)
R

[,1] [,2] [,3] [,4] [,5]
[1,] 6    8    10   12   14  
[2,] 7    9    11   13   15

### Pregunta 6

In [12]:
Q <- matrix(32:1,nrow=4)
cat("Matriz Q\n")
print(Q)
cat("\nSlide\n")
print(Q[1:3,7:8])

Matriz Q
     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]   32   28   24   20   16   12    8    4
[2,]   31   27   23   19   15   11    7    3
[3,]   30   26   22   18   14   10    6    2
[4,]   29   25   21   17   13    9    5    1

Slide
     [,1] [,2]
[1,]    8    4
[2,]    7    3
[3,]    6    2


# Operaciones con Matrices

### Pregunta 7:Obtener el estimador de la varianza del termino de perturbación

In [13]:
set.seed(6)

x1 <- runif(6)
x2 <- runif(6)
x3 <- runif(6)
x4 <- runif(6)
u <- rnorm(6)

Y <- 1 + 0.9*x1 + 1.4*x2 + 1.5*x3+ x4 + u
Y

[1] 3.830032 3.686721 3.464760 2.699423 5.231537 3.325284

In [14]:
X <- cbind(matrix(1,6), x1,x2,x3,x4) #MATRIZ x
X

x1        x2        x3         x4       
[1,] 1 0.6062683 0.9579337 0.09523258 0.1472278
[2,] 1 0.9376420 0.7627319 0.29537280 0.7005260
[3,] 1 0.2643521 0.5096485 0.76993170 0.9579925
[4,] 1 0.3800939 0.0644768 0.25589353 0.8286251
[5,] 1 0.8074834 0.6435728 0.51789573 0.1192788
[6,] 1 0.9780757 0.9159089 0.67784993 0.2403410

In [15]:
#install.packages("matlib")
library(matlib)

FORMULA DEL ESTIMADOR DE LA VARIANZA

\begin{equation}
 \hat{\sigma}^2 = {\frac{\sum(\hat{U})^2}{N-K}} = {\frac{\sum(Y- \hat{Y})^2}{N-K}} = {\frac{\sum({Y-XB})^2}{N-K}}
\end{equation}

In [16]:
B <- inv(t(X) %*% X) %*% (t(X) %*% Y)  # Matriz Betas Estimados
print(B)

             [,1]
[1,]  4.338554410
[2,]  0.004128174
[3,] -0.211809314
[4,]  0.702713015
[5,] -1.612968645


In [17]:
Y_est = X %*% B   # matriz Y estimados
print(Y_est)


         [,1]
[1,] 3.967605
[2,] 3.258507
[3,] 3.227526
[4,] 3.169740
[5,] 4.377112
[6,] 4.237266


In [18]:
U <- Y - Y_est  # Matriz errores estimados
print(U)

           [,1]
[1,] -0.1375732
[2,]  0.4282139
[3,]  0.2372337
[4,] -0.4703176
[5,]  0.8544245
[6,] -0.9119820


In [19]:
S2= sum(U^2)/(5-4)  
print (S2)

[1] 2.041525


### Pregunta 8: Matriz de varianza y covarianza de los coeficientes¶

\begin{equation}
 \Sigma = (\frac{\hat{U}'\hat{U}}{n-k})(X'X)^{-1}
\end{equation}

In [20]:
CV <- S2*(inv(t(X) %*% X))
print(CV)

                                                        
[1,]  9.793064 -4.7472326 -4.291990 -1.1043513 -6.153825
[2,] -4.747233  9.0214455 -3.546073 -0.2509666  2.323332
[3,] -4.291990 -3.5460734  8.434358 -1.0779197  3.390503
[4,] -1.104351 -0.2509666 -1.077920  6.3358146 -1.593939
[5,] -6.153825  2.3233324  3.390503 -1.5939394  6.274551


### Pregunta 9: Matriz generador de residuos


\begin{equation}
 M = I - X(X'X)^{-1}X'
\end{equation}

In [21]:
I <- diag(6)
print(I)

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    0    0    0    0    0
[2,]    0    1    0    0    0    0
[3,]    0    0    1    0    0    0
[4,]    0    0    0    1    0    0
[5,]    0    0    0    0    1    0
[6,]    0    0    0    0    0    1


In [22]:
M = I - X %*% (inv(t(X) %*% X)%*% t(X))
print(M)

             [,1]        [,2]        [,3]        [,4]        [,5]        [,6]
[1,]  0.009270697 -0.02885625 -0.01598659  0.03169349 -0.05757748  0.06145611
[2,] -0.028856246  0.08981878  0.04976030 -0.09865009  0.17921734 -0.19129011
[3,] -0.015986586  0.04976030  0.02756758 -0.05465291  0.09928779 -0.10597621
[4,]  0.031693487 -0.09865009 -0.05465291  0.10834971 -0.19683863  0.21009842
[5,] -0.057577482  0.17921734  0.09928779 -0.19683863  0.35759620 -0.38168525
[6,]  0.061456113 -0.19129011 -0.10597621  0.21009842 -0.38168525  0.40739701
