## Grupo 1

In [5]:
a <- "Primer trabajo grupal"

In [6]:
b <- "2022-1"

In [11]:
# install.packages("devtools")
# library(glue)

also installing the dependencies 'utf8', 'pillar', 'pkgconfig', 'vctrs', 'askpass', 'credentials', 'sys', 'zip', 'gitcreds', 'ini', 'fastmap', 'evaluate', 'highr', 'xfun', 'diffobj', 'fansi', 'rematch2', 'tibble', 'clipr', 'curl', 'gert', 'gh', 'glue', 'purrr', 'rappdirs', 'rprojroot', 'whisker', 'yaml', 'processx', 'R6', 'mime', 'openssl', 'cachem', 'prettyunits', 'xopen', 'brew', 'commonmark', 'knitr', 'stringi', 'stringr', 'xml2', 'cpp11', 'brio', 'magrittr', 'praise', 'ps', 'waldo', 'usethis', 'callr', 'cli', 'desc', 'ellipsis', 'fs', 'httr', 'lifecycle', 'memoise', 'pkgbuild', 'pkgload', 'rcmdcheck', 'remotes', 'rlang', 'roxygen2', 'rstudioapi', 'rversions', 'sessioninfo', 'testthat', 'withr'




  There are binary versions available but the source versions are later:
            binary source needs_compilation
utf8         1.2.1  1.2.2              TRUE
pillar       1.6.0  1.7.0             FALSE
vctrs        0.3.8  0.4.0              TRUE
credentials  1.3.0  1.3.2             FALSE
zip          2.1.1  2.2.0              TRUE
evaluate      0.14   0.15             FALSE
xfun          0.22   0.30              TRUE
diffobj      0.3.4  0.3.5              TRUE
fansi        0.4.2  1.0.3              TRUE
tibble       3.1.1  3.1.6              TRUE
clipr        0.7.1  0.8.0             FALSE
curl         4.3.1  4.3.2              TRUE
gert         1.3.0  1.6.0              TRUE
glue         1.4.2  1.6.2              TRUE
rprojroot    2.0.2  2.0.3             FALSE
yaml         2.2.1  2.3.5              TRUE
processx     3.5.2  3.5.3              TRUE
R6           2.5.0  2.5.1             FALSE
mime          0.10   0.12              TRUE
openssl      1.4.4  2.0.0              TRUE
ca

installing the source packages 'pillar', 'credentials', 'evaluate', 'clipr', 'rprojroot', 'R6', 'brew', 'knitr', 'cpp11', 'waldo', 'usethis', 'desc', 'lifecycle', 'memoise', 'pkgbuild', 'pkgload', 'rcmdcheck', 'remotes', 'rversions', 'sessioninfo', 'withr', 'devtools'

Warning message in install.packages("devtools"):
"installation of package 'waldo' had non-zero exit status"Warning message in install.packages("devtools"):
"installation of package 'sessioninfo' had non-zero exit status"Warning message in install.packages("devtools"):
"installation of package 'knitr' had non-zero exit status"Warning message in install.packages("devtools"):
"installation of package 'rcmdcheck' had non-zero exit status"Warning message in install.packages("devtools"):
"installation of package 'devtools' had non-zero exit status"

In [13]:
c <- glue('{a}: Ciclo {b}')
c

Primer trabajo grupal: Ciclo 2022-1

In [14]:
d <- "25"

In [15]:
e <- "30"

In [17]:
f <- glue('{d} x {e} es igual a 750')
f

25 x 30 es igual a 750

### Diccionarios y listas

In [28]:
dic1 <- list('Breña'=list('Population'="93111",'Poverty'="5.4%"),"Pueblo_Libre"=list("Population"="94010","Poverty"="1.2%"),
"San_Miguel"=list("Population"="173309","Poverty"="2.1%"),"La_Punta"=list("Population"="3935","Poverty"="3.7%"),"Bellavista"=list("Population"="16370",
"Poverty"="6.3%"))
dic1

$Breña
$Breña$Population
[1] "93111"

$Breña$Poverty
[1] "5.4%"


$Pueblo_Libre
$Pueblo_Libre$Population
[1] "94010"

$Pueblo_Libre$Poverty
[1] "1.2%"


$San_Miguel
$San_Miguel$Population
[1] "173309"

$San_Miguel$Poverty
[1] "2.1%"


$La_Punta
$La_Punta$Population
[1] "3935"

$La_Punta$Poverty
[1] "3.7%"


$Bellavista
$Bellavista$Population
[1] "16370"

$Bellavista$Poverty
[1] "6.3%"

In [24]:
dic1$Breña$Poverty

[1] "5.4%"

In [25]:
dic1$Breña$Population

[1] "93111"

In [29]:
dic1$Pueblo_Libre$Poverty

[1] "1.2%"

In [30]:
dic1$Pueblo_Libre$Population

[1] "94010"

In [31]:
dic1$Bellavista$Poverty

[1] "6.3%"

In [32]:
dic1$Bellavista$Population

[1] "16370"

### Matrices

In [39]:
f <- c(1,2,3,4,5,6,7,8,9,10)

In [40]:
m1 <- matrix(f, nrow=2, byrow=TRUE)
print(m1)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    3    4    5
[2,]    6    7    8    9   10


In [41]:
m2 <- matrix(f, nrow=2, byrow=FALSE)
print(m2)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


In [59]:
e <- matrix(seq(1,32,1),4,8)
e

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    5     9   13   17   21   25   29  
[2,] 2    6    10   14   18   22   26   30  
[3,] 3    7    11   15   19   23   27   31  
[4,] 4    8    12   16   20   24   28   32

In [69]:
e[,c(-1:-6)]

[,1] [,2]
[1,] 25   29  
[2,] 26   30  
[3,] 27   31  
[4,] 28   32

In [70]:
e[c(1:3),]

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 1    5     9   13   17   21   25   29  
[2,] 2    6    10   14   18   22   26   30  
[3,] 3    7    11   15   19   23   27   31

### Operaciones con matrices

also installing the dependencies 'lattice', 'Matrix'




  There are binary versions available but the source versions are later:
         binary  source needs_compilation
lattice 0.20-44 0.20-45              TRUE
Matrix    1.3-3   1.4-1              TRUE

  Binaries will be installed
package 'lattice' successfully unpacked and MD5 sums checked
package 'Matrix' successfully unpacked and MD5 sums checked
package 'RcppEigen' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\PERSONAL\AppData\Local\Temp\RtmpiQwhJ3\downloaded_packages


Warning message:
"package 'RcppEigen' was built under R version 3.6.3"