## Trabajo Grupal 1

### Grupo 1

In [1]:
c1="Primer trabajo grupal"
c2="2022-1"
print(f'{c1}: Laboratorio de R y Python ciclo {c2}')

Primer trabajo grupal: Laboratorio de R y Python ciclo 2022-1


In [2]:
d1="25"
d2="30"
print(f'{d1} x {d2} es 750')

25 x 30 es 750


### Diccionarios y listas

In [3]:
dis1=["Breña","Pueblo libre","San Miguel","La Punta","Bellavista"]

In [4]:
dis1[0]

'Breña'

In [5]:
dis1[-1]

'Bellavista'

In [6]:
dic1={"Breña":{"Population":"93111","Poverty":"5.4%"},"Pueblo Libre":{"Population": "94010",
"Poverty":"1.2%"},"San Miguel":{"Population":"173309","Poverty":"2.1%"},"La Punta":{"Population":"3935","Poverty":"3.7%"},
"Bellavista":{"Population":"16370","Poverty":"6.3%"}}

In [7]:
dic1['Breña']['Poverty']

'5.4%'

In [8]:
dic1['Breña']['Population']

'93111'

In [9]:
dic1['Pueblo Libre']['Poverty']

'1.2%'

In [10]:
dic1['Pueblo Libre']['Population']

'94010'

In [11]:
dic1['Bellavista']['Poverty']

'6.3%'

In [12]:
dic1['Bellavista']['Population']

'16370'

### Matrices

In [13]:
import numpy as np

In [14]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print (a)

[[1 2 3 4]
 [5 6 7 8]]


In [15]:
b=np.array([[20,21,22,23],[24,25,26,27]])
print (b)

[[20 21 22 23]
 [24 25 26 27]]


In [16]:
con1 = np.concatenate((a,b), axis = 0)
print (con1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [20 21 22 23]
 [24 25 26 27]]


In [17]:
con2 = np.concatenate((a,b), axis = 1)
print (con2)

[[ 1  2  3  4 20 21 22 23]
 [ 5  6  7  8 24 25 26 27]]


In [18]:
c=np.array([[23,1,76,23,54,6,9,40],[48,58,67,29,45,21,18,28],[28,67,84,14,74,25,25,75],[86,11,22,33,44,55,66,77]])
print (c)

[[23  1 76 23 54  6  9 40]
 [48 58 67 29 45 21 18 28]
 [28 67 84 14 74 25 25 75]
 [86 11 22 33 44 55 66 77]]


In [19]:
c[:,6:8]

array([[ 9, 40],
       [18, 28],
       [25, 75],
       [66, 77]])

In [20]:
c[0:3]

array([[23,  1, 76, 23, 54,  6,  9, 40],
       [48, 58, 67, 29, 45, 21, 18, 28],
       [28, 67, 84, 14, 74, 25, 25, 75]])

### Operaciones con matrices

In [27]:
import random

In [28]:
random.seed(23)
x1 = np.random.rand(50)
x2 = np.random.rand(50)
x3 = np.random.rand(50)
e = np.random.rand(0,1,50)

# Poblacional regression (Data Generating Process GDP)

Y = 13 + 5*x1 + 2*x2 + 5*x3 + e

In [29]:
X = np.column_stack((np.ones(50),x1,x2,x3))
X

array([[1.        , 0.86858375, 0.98686754, 0.48883667],
       [1.        , 0.26892347, 0.35475588, 0.60971897],
       [1.        , 0.83649186, 0.66828377, 0.75360321],
       [1.        , 0.45781943, 0.1786522 , 0.40227691],
       [1.        , 0.21444909, 0.38688774, 0.68057568],
       [1.        , 0.53594035, 0.02368052, 0.42364194],
       [1.        , 0.32663927, 0.85600662, 0.60448927],
       [1.        , 0.52230223, 0.40915826, 0.39910373],
       [1.        , 0.99926961, 0.47436002, 0.88292715],
       [1.        , 0.51282658, 0.63857481, 0.04331773],
       [1.        , 0.77705933, 0.42690387, 0.44032838],
       [1.        , 0.50593266, 0.86798923, 0.29296889],
       [1.        , 0.15863734, 0.42535146, 0.40807427],
       [1.        , 0.98478463, 0.220301  , 0.86886533],
       [1.        , 0.48014444, 0.63267258, 0.17166793],
       [1.        , 0.88669255, 0.17345967, 0.42625217],
       [1.        , 0.80506514, 0.15882373, 0.82254798],
       [1.        , 0.99593617,