# #Grupo 4 - Homework1

1- Use f-string para concaternar textos o valores numéricos. De 2 ejemplos.

In [204]:
#Example_1
a1 <- "Chile"
a1

[1] "Chile"

In [205]:
a2 <- "Mundial"
a2

[1] "Mundial"

In [206]:
a3 <- "Qatar 2022"
a3

[1] "Qatar 2022"

In [207]:
#install.packages("devtools")

library(glue)
A <- glue('{a1} no va al {a2} de {a3}')
A 

Chile no va al Mundial de Qatar 2022

In [208]:
#Example_2
b1 <- "07 de abril de 2022"
b1

[1] "07 de abril de 2022"

In [209]:
b2 <- "el tipo de cambio del BCR"
b2

[1] "el tipo de cambio del BCR"

In [210]:
b3 <- "S/.3.71"
b3

[1] "S/.3.71"

In [211]:
B <- glue('Hoy, {b1}, {b2} cotiza en {b3}')
B

Hoy, 07 de abril de 2022, el tipo de cambio del BCR cotiza en S/.3.71

# Diccionarios y listas

2- Crear una Lista de 3 distritos de Lima, añadir 2 distritos del Callao. Extraer el primer y último elemento usando el Indexing

In [212]:
List1 <- list()

In [213]:
Dist_Lima <- list("MAGDALENA DEL MAR", "PUEBO LIBRE", "SAN MIGUEL")
Dist_Lima

[[1]]
[1] "MAGDALENA DEL MAR"

[[2]]
[1] "PUEBO LIBRE"

[[3]]
[1] "SAN MIGUEL"

In [214]:
Dist_Callao <- list("VENTANILLA", "LA PUNTA")
Dist_Callao

[[1]]
[1] "VENTANILLA"

[[2]]
[1] "LA PUNTA"

In [215]:
Districts <- append(Dist_Lima, Dist_Callao)
Districts

[[1]]
[1] "MAGDALENA DEL MAR"

[[2]]
[1] "PUEBO LIBRE"

[[3]]
[1] "SAN MIGUEL"

[[4]]
[1] "VENTANILLA"

[[5]]
[1] "LA PUNTA"

In [216]:
#The first element of the new list "Districts" comes from the list "Dist_Lima"
Dist_Lima[1]

[[1]]
[1] "MAGDALENA DEL MAR"

In [217]:
#The last element of the new list "Districts" comes from the list "Dist_Callao" 
Dist_Callao[2]

[[1]]
[1] "LA PUNTA"

In [218]:
Districts[c(1,5)]

[[1]]
[1] "MAGDALENA DEL MAR"

[[2]]
[1] "LA PUNTA"

3- Crear un diccionario con los 5 distritos del ejercicio a. Incluir información de población proyectada e incidencia de pobreza (limite superior).Use la información del Mapa de Pobreza 2018

In [219]:
Population <- list ('MAGDALENA DEL MAR' = 65139, 'PUEBO LIBRE' = 94010, 'SAN MIGUEL' = 173309, 'VENTANILLA' = 369618, 'LA PUNTA' = 3935)
print(Population)

$`MAGDALENA DEL MAR`
[1] 65139

$`PUEBO LIBRE`
[1] 94010

$`SAN MIGUEL`
[1] 173309

$VENTANILLA
[1] 369618

$`LA PUNTA`
[1] 3935



In [220]:
Poverty <- list ('MAGDALENA DEL MAR' = 1.2, 'PUEBO LIBRE' = 1.2, 'SAN MIGUEL' = 2.1, 'VENTANILLA' = 29.4, 'LA PUNTA' = 3.7)
print(Poverty)

$`MAGDALENA DEL MAR`
[1] 1.2

$`PUEBO LIBRE`
[1] 1.2

$`SAN MIGUEL`
[1] 2.1

$VENTANILLA
[1] 29.4

$`LA PUNTA`
[1] 3.7



4- Muestre la información de pobreza y de población de 3 distritos

In [221]:
Population[c(2:4)]

$`PUEBO LIBRE`
[1] 94010

$`SAN MIGUEL`
[1] 173309

$VENTANILLA
[1] 369618

In [222]:
Poverty[c(2:4)]

$`PUEBO LIBRE`
[1] 1.2

$`SAN MIGUEL`
[1] 2.1

$VENTANILLA
[1] 29.4

In [223]:
#Format = District: Population | Poverty

Map(c, Population, Poverty)[(2:4)]

$`PUEBO LIBRE`
[1] 94010.0     1.2

$`SAN MIGUEL`
[1] 173309.0      2.1

$VENTANILLA
[1] 369618.0     29.4

# Matrices

5- Crear matrices y dar dos ejemplos de concatenación. Unión vertical y horizontal.

In [224]:
A1 <- c(2, 5, 9, 4, 8, 6)
print(A1)

[1] 2 5 9 4 8 6


In [225]:
A2 <- c(1, 3, 6, 9, 7, 0)
print(A2)

[1] 1 3 6 9 7 0


In [226]:
A <- matrix(c(A1, A2), nrow = 2, byrow = TRUE)
print(A)

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    2    5    9    4    8    6
[2,]    1    3    6    9    7    0


In [227]:
B <- matrix(c(A1, A2), nrow = 2, byrow = FALSE)
print(B)

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    2    9    8    1    6    7
[2,]    5    4    6    3    9    0


In [228]:
A <- matrix(c(A1, A2), nrow = 2, byrow =TRUE)
A

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 2    5    9    4    8    6   
[2,] 1    3    6    9    7    0

In [229]:
B <- matrix(c(A1, A2), nrow = 2, byrow =FALSE)
B

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 2    9    8    1    6    7   
[2,] 5    4    6    3    9    0

6- Crear una matriz de dimensión 4x8, seleccionar las ultimas dos columnas y primeras 3 filas.

In [230]:
Matrix <- matrix((16:47), 4, 8)
Matrix                     

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 16   20   24   28   32   36   40   44  
[2,] 17   21   25   29   33   37   41   45  
[3,] 18   22   26   30   34   38   42   46  
[4,] 19   23   27   31   35   39   43   47

In [231]:
Matrix[,7:8]

[,1] [,2]
[1,] 40   44  
[2,] 41   45  
[3,] 42   46  
[4,] 43   47

In [232]:
Matrix[1:3,]

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 16   20   24   28   32   36   40   44  
[2,] 17   21   25   29   33   37   41   45  
[3,] 18   22   26   30   34   38   42   46

# Operaciones con matrices

7- Obtener el estimador de la varianza del termino de perturbación

In [233]:
set.seed(456)

x1 <- runif(20)
x2 <- runif(20)
x3 <- runif(20)
x4 <- runif(20)
e <- rnorm(20)

# Poblacional regression (Data Generating Process GDP)

Y <- 20 + 5*x1 + 9*x2 + 6*x3 + 4*x4 + e

In [237]:
X <- cbind(matrix(1,20), x1,x2,x3,x4)
X

x1         x2         x3         x4         
 [1,] 1 0.08955160 0.17988314 0.31753470 0.298474103
 [2,] 1 0.21051232 0.72174360 0.42369873 0.408579878
 [3,] 1 0.73295527 0.90508758 0.04296139 0.276325333
 [4,] 1 0.85213354 0.44576667 0.12927385 0.626006929
 [5,] 1 0.78839789 0.83860146 0.07681441 0.022808742
 [6,] 1 0.33195997 0.70349283 0.07841957 0.328526801
 [7,] 1 0.08243274 0.95092900 0.58247762 0.616443433
 [8,] 1 0.28552695 0.64315218 0.54410322 0.419175668
 [9,] 1 0.23750327 0.07481986 0.48570649 0.567740781
[10,] 1 0.38523617 0.25349037 0.92824613 0.531089413
[11,] 1 0.37294591 0.97425399 0.87166240 0.965288136
[12,] 1 0.21790856 0.21730407 0.79849677 0.847544263
[13,] 1 0.75510504 0.95880078 0.32173416 0.254433440
[14,] 1 0.82168107 0.50185606 0.42532838 0.075905390
[15,] 1 0.59891816 0.65080078 0.37131065 0.444230469
[16,] 1 0.65103356 0.94830108 0.89427371 0.001509915
[17,] 1 0.84311724 0.98869716 0.93116707 0.335790524
[18,] 1 0.45323814 0.91811448 0.61723848 0.374027789
[19,] 1 0.71675710 0.93796142 0.13799364 0.484550527
[20,] 1 0.29122217 0.52833515 0.25414065 0.602876637

In [159]:
trX<-(t(X))
trX

[,1]      [,2]      [,3]       [,4]      [,5]       [,6]       [,7]      
   1.0000000 1.0000000 1.00000000 1.0000000 1.00000000 1.00000000 1.00000000
x1 0.0895516 0.2105123 0.73295527 0.8521335 0.78839789 0.33195997 0.08243274
x2 0.1798831 0.7217436 0.90508758 0.4457667 0.83860146 0.70349283 0.95092900
x3 0.3175347 0.4236987 0.04296139 0.1292738 0.07681441 0.07841957 0.58247762
x4 0.2984741 0.4085799 0.27632533 0.6260069 0.02280874 0.32852680 0.61644343
   [,8]      [,9]       [,10]     [,11]     [,12]     [,13]     [,14]     
   1.0000000 1.00000000 1.0000000 1.0000000 1.0000000 1.0000000 1.00000000
x1 0.2855269 0.23750327 0.3852362 0.3729459 0.2179086 0.7551050 0.82168107
x2 0.6431522 0.07481986 0.2534904 0.9742540 0.2173041 0.9588008 0.50185606
x3 0.5441032 0.48570649 0.9282461 0.8716624 0.7984968 0.3217342 0.42532838
x4 0.4191757 0.56774078 0.5310894 0.9652881 0.8475443 0.2544334 0.07590539
   [,15]     [,16]       [,17]     [,18]     [,19]     [,20]    
   1.0000000 1.000000000 1.0000000 1.0000000 1.0000000 1.0000000
x1 0.5989182 0.651033560 0.8431172 0.4532381 0.7167571 0.2912222
x2 0.6508008 0.948301075 0.9886972 0.9181145 0.9379614 0.5283351
x3 0.3713107 0.894273708 0.9311671 0.6172385 0.1379936 0.2541407
x4 0.4442305 0.001509915 0.3357905 0.3740278 0.4845505 0.6028766

In [160]:
X_X <- trX %*% X
X_X

x1       x2        x3       x4      
   20.000000 9.718137 13.341392 9.232582 8.481328
x1  9.718137 6.069881  7.113493 4.156046 3.527424
x2 13.341392 7.113493 10.626817 6.139895 5.306466
x3  9.232582 4.156046  6.139895 5.994928 4.306311
x4  8.481328 3.527424  5.306466 4.306311 4.761666

In [166]:
invX_X <- solve(X_X)
invX_X

x1         x2          x3          x4         
    0.9249112 -0.5615234 -0.32001395 -0.22543146 -0.67094639
x1 -0.5615234  1.1067485 -0.31515698  0.10988518  0.43213075
x2 -0.3200140 -0.3151570  0.70885924 -0.06956121  0.07641238
x3 -0.2254315  0.1098852 -0.06956121  0.63764433 -0.17901796
x4 -0.6709464  0.4321308  0.07641238 -0.17901796  1.16170163

In [167]:
W <- invX_X %*% trX
W

[,1]        [,2]        [,3]        [,4]       [,5]        [,6]      
    0.54521830  0.20608534  0.02861467 -0.1453928  0.18122333  0.2752783
x1 -0.35523150 -0.33288356  0.08855862  0.5258098  0.06504086 -0.2652542
x2 -0.22000592  0.12700380  0.10869601 -0.2337417  0.02236691  0.0936925
x3 -0.07906199 -0.05547869 -0.22992265 -0.1924384 -0.15223526 -0.2466982
x4 -0.32860966 -0.12602918  0.02826274  0.4354397 -0.25343009 -0.1061291
   [,7]        [,8]        [,9]         [,10]       [,11]       [,12]      
    0.02940343  0.15486106  0.277186976  0.06188319 -0.44043827 -0.01565298
x1 -0.43959314 -0.20728316 -0.023536777  0.11644749  0.05710449  0.06515461
x2  0.33466766  0.04008633 -0.332231928 -0.28572295  0.26618455 -0.22543289
x3 -0.02146200  0.03310963  0.003534256  0.29608352  0.13078615  0.14082882
x4  0.04918745 -0.10886383  0.009998440 -0.03430949  0.52999364  0.28147160
   [,13]       [,14]       [,15]        [,16]       [,17]        [,18]      
   -0.04916778  0.15610626 -0.001420645  0.05326053 -0.300127546 -0.01349965
x1  0.11731759  0.26924584  0.128991201 -0.04093673  0.307427449 -0.11979864
x2  0.11872587 -0.24701341 -0.039325153  0.08492887  0.076004329  0.17360331
x3 -0.04954815  0.08756919 -0.047650826  0.35010076  0.332080515  0.08712846
x4 -0.03339849 -0.26548673  0.087185780 -0.47548982 -0.007668038 -0.08092103
   [,19]      [,20]       
   -0.1339410  0.130519291
x1  0.1606940 -0.117274346
x2  0.1464043 -0.008890494
x3 -0.2106686 -0.176056498
x4  0.2486580  0.150138033

In [238]:
Z_betas <- W %*% Y
Z_betas

[,1]     
   20.825526
x1  4.890070
x2  9.502416
x3  5.746661
x4  2.464955

In [172]:
#Procedimiento directo
Betas <- solve(trX %*% X) %*% (trX %*% Y)
Betas

[,1]     
   20.825526
x1  4.890070
x2  9.502416
x3  5.746661
x4  2.464955

In [176]:
#Tomando en cuenta el modelo estimado (Y_hat=X*beta)
Y_hat <- X %*% Betas
Y_hat

[,1]    
 [1,] 25.53325
 [2,] 32.15524
 [3,] 33.93826
 [4,] 31.51435
 [5,] 33.14724
 [6,] 30.39417
 [7,] 35.13156
 [8,] 32.49330
 [9,] 26.88855
[10,] 31.76156
[11,] 39.29556
[12,] 30.63388
[13,] 36.10503
[14,] 32.24377
[15,] 33.16726
[16,] 38.16309
[17,] 40.52225
[18,] 36.23522
[19,] 35.23082
[20,] 30.21661

In [177]:
#Para hallar la SRC (tr_e_hat*e_hat). Primero se halla e_hat (e_hat = Y - Y_hat) y su traspuesta

e_hat <- Y - Y_hat
e_hat

[,1]       
 [1,] -0.39638465
 [2,] -0.03743493
 [3,] -1.01424158
 [4,]  0.12133750
 [5,]  0.97316236
 [6,] -0.49745811
 [7,] -0.08224430
 [8,]  0.43408206
 [9,] -1.01785433
[10,]  0.54891097
[11,] -0.23637322
[12,]  0.33603583
[13,] -0.07337798
[14,]  0.13377560
[15,]  0.30767764
[16,] -0.27007406
[17,] -0.89139998
[18,]  1.05135584
[19,]  0.10248459
[20,]  0.50802075

In [239]:
#Sacando la traspuesta de e_hat

tr_e_hat <- (t(e_hat))
tr_e_hat

[,1]       [,2]        [,3]      [,4]      [,5]      [,6]       [,7]      
[1,] -0.3963846 -0.03743493 -1.014242 0.1213375 0.9731624 -0.4974581 -0.0822443
     [,8]      [,9]      [,10]    [,11]      [,12]     [,13]       [,14]    
[1,] 0.4340821 -1.017854 0.548911 -0.2363732 0.3360358 -0.07337798 0.1337756
     [,15]     [,16]      [,17]   [,18]    [,19]     [,20]    
[1,] 0.3076776 -0.2700741 -0.8914 1.051356 0.1024846 0.5080207

In [240]:
#Hallando la SRC ((e_hat)'*e_hat)

SRC <- tr_e_hat %*%  e_hat
SRC

[,1]    
[1,] 6.457172

In [241]:
#Hallando la SD, teniendo en cuenta que se tiene 20 observaciones con k=5 (4 variables explicativas y la constante). Entonces, n-k=20-5=15
SD <- SRC/15
SD

[,1]     
[1,] 0.4304781

8- matriz de varianza y covarianza de los coeficientes

In [235]:
#Para hallar la matriz de varianza y covarianza de los betas, se necesita: V(betas)=SD*[(X'*X)^-1]= SD*invX_X

Varianza_betas <- 0.4304781 * invX_X

Varianza_betas

x1          x2          x3          x4         
    0.39815400 -0.24172351 -0.13775900 -0.09704331 -0.28882773
x1 -0.24172351  0.47643100 -0.13566818  0.04730316  0.18602283
x2 -0.13775900 -0.13566818  0.30514838 -0.02994458  0.03289385
x3 -0.09704331  0.04730316 -0.02994458  0.27449192 -0.07706331
x4 -0.28882773  0.18602283  0.03289385 -0.07706331  0.50008711

# Matriz generadora de residuos 

\begin{equation}
 M = I - X(X'X)^{-1}X'
\end{equation}

9 - Matriz generador de residuos

In [193]:
#Operando primero las matrices: X(X'X)^{-1} = X*invX_X

G <- X %*% invX_X
G

x1          x2           x3           x4          
 [1,]  0.545218300 -0.35523150 -0.220005921 -0.079061987 -0.328609658
 [2,]  0.206085337 -0.33288356  0.127003805 -0.055478686 -0.126029176
 [3,]  0.028614669  0.08855862  0.108696006 -0.229922649  0.028262740
 [4,] -0.145392766  0.52580982 -0.233741727 -0.192438438  0.435439732
 [5,]  0.181223330  0.06504086  0.022366915 -0.152235259 -0.253430094
 [6,]  0.275278255 -0.26525415  0.093692496 -0.246698203 -0.106129117
 [7,]  0.029403431 -0.43959314  0.334667661 -0.021461996  0.049187453
 [8,]  0.154861056 -0.20728316  0.040086331  0.033109630 -0.108863828
 [9,]  0.277186976 -0.02353678 -0.332231928  0.003534256  0.009998440
[10,]  0.061883188  0.11644749 -0.285722946  0.296083524 -0.034309492
[11,] -0.440438272  0.05710449  0.266184554  0.130786146  0.529993640
[12,] -0.015652982  0.06515461 -0.225432888  0.140828818  0.281471602
[13,] -0.049167784  0.11731759  0.118725866 -0.049548149 -0.033398494
[14,]  0.156106257  0.26924584 -0.247013412  0.087569192 -0.265486726
[15,] -0.001420645  0.12899120 -0.039325153 -0.047650826  0.087185780
[16,]  0.053260531 -0.04093673  0.084928872  0.350100759 -0.475489817
[17,] -0.300127546  0.30742745  0.076004329  0.332080515 -0.007668038
[18,] -0.013499654 -0.11979864  0.173603311  0.087128457 -0.080921028
[19,] -0.133940971  0.16069404  0.146404324 -0.210668606  0.248658048
[20,]  0.130519291 -0.11727435 -0.008890494 -0.176056498  0.150138033

In [194]:
#Entonces, M ahora es: M = I - G*X'; pero H = G*trX. Entonces, M = I - H

H <- G %*% trX
H

[,1]         [,2]         [,3]         [,4]         [,5]       
 [1,]  0.350644999  0.143888071 -0.008474908 -0.071490248  0.06708898
 [2,]  0.143888071  0.152674196  0.039837649 -0.107028926  0.04301009
 [3,] -0.008474908  0.039837649  0.189835496  0.140501182  0.17256999
 [4,] -0.071490248 -0.107028926  0.140501182  0.446184175  0.06828822
 [5,]  0.067088977  0.043010087  0.172569993  0.068288219  0.23378405
 [6,]  0.158365989  0.139173010  0.125734079 -0.007317903  0.12335245
 [7,]  0.058104483  0.189411484  0.022774565 -0.167987731 -0.03704478
 [8,]  0.121529795  0.109706389  0.010554013 -0.067772029  0.02511615
 [9,]  0.219422823  0.038028548 -0.037848761  0.115748558 -0.01948002
[10,]  0.104690804 -0.008389844 -0.108130724  0.050544109 -0.06395661
[11,] -0.187723845  0.035658586 -0.005593478  0.075565501 -0.15005971
[12,]  0.078360163  0.010030747 -0.088106135  0.133785639 -0.13609587
[13,] -0.043006867  0.026579207  0.132920559  0.076413532  0.13832105
[14,]  0.084349449 -0.036864106  0.060284026  0.120553196  0.16190446
[15,]  0.013948699  0.012783675  0.079575922  0.139386138  0.06562594
[16,]  0.034119595  0.060001389 -0.016225264 -0.196165619  0.10825503
[17,] -0.155766655 -0.042985557  0.006141362  0.033850971  0.03131862
[18,]  0.010513971  0.090431849  0.037202134 -0.077591214  0.04248236
[19,] -0.085891497  0.017890143  0.176009212  0.196681701  0.10501395
[20,]  0.107326204  0.086163404  0.070439076  0.097850749  0.02050565
      [,6]         [,7]         [,8]         [,9]        [,10]        
 [1,]  0.158365989  0.058104483  0.121529795  0.21942282  0.1046908038
 [2,]  0.139173010  0.189411484  0.109706389  0.03802855 -0.0083898442
 [3,]  0.125734079  0.022774565  0.010554013 -0.03784876 -0.1081307243
 [4,] -0.007317903 -0.167987731 -0.067772029  0.11574856  0.0505441091
 [5,]  0.123352454 -0.037044775  0.025116153 -0.01948002 -0.0639566123
 [6,]  0.198924267  0.133388761  0.081083549  0.03921284 -0.0885177967
 [7,]  0.133388761  0.329231899  0.128070620 -0.03246010 -0.0489077956
 [8,]  0.081083549  0.128070620  0.093839728  0.06290501  0.0580870443
 [9,]  0.039212839 -0.032460100  0.062905008  0.25413250  0.1924928883
[10,] -0.088517797 -0.048907796  0.058087044  0.19249289  0.2909319344
[11,] -0.049849633  0.220282720  0.040385375 -0.04253720  0.0519114104
[12,] -0.049099978  0.030888177  0.052574224  0.21115897  0.2325122584
[13,]  0.058441909  0.023953924  0.019729203 -0.05544897 -0.0376074070
[14,] -0.008639435 -0.169241742  0.010477089  0.09337680  0.1375025434
[15,]  0.038640415 -0.002193414  0.020736950  0.05262749  0.0403746324
[16,] -0.029338370  0.041460614  0.087371369 -0.05001646  0.1314709413
[17,] -0.121082984 -0.013808184  0.014005446 -0.06448569  0.1417510319
[18,]  0.049108529  0.142576579  0.077434703 -0.03258656  0.0222566993
[19,]  0.087567702  0.049099467 -0.004292296 -0.04597145 -0.0984163894
[20,]  0.120852596  0.102400451  0.058457667  0.10172877 -0.0005997273
      [,11]        [,12]         [,13]       [,14]         [,15]       
 [1,] -0.187723845  0.0783601628 -0.04300687  0.0843494489  0.013948699
 [2,]  0.035658586  0.0100307471  0.02657921 -0.0368641057  0.012783675
 [3,] -0.005593478 -0.0881061350  0.13292056  0.0602840263  0.079575922
 [4,]  0.075565501  0.1337856387  0.07641353  0.1205531956  0.139386138
 [5,] -0.150059706 -0.1360958744  0.13832105  0.1619044566  0.065625943
 [6,] -0.049849633 -0.0490999783  0.05844191 -0.0086394346  0.038640415
 [7,]  0.220282720  0.0308881769  0.02395392 -0.1692417425 -0.002193414
 [8,]  0.040385375  0.0525742241  0.01972920  0.0104770886  0.020736950
 [9,] -0.042537196  0.2111589733 -0.05544897  0.0933767995  0.052627492
[10,]  0.051911410  0.2325122584 -0.03760741  0.1375025434  0.040374632
[11,]  0.465787917  0.1834736571  0.03482605 -0.1640738269  0.050997374
[12,]  0.183473657  0.3005682797 -0.06567440  0.0060121749  0.053986902
[13,]  0.034826051 -0.0656744030  0.12881474  0.0832037921  0.065128352
[14,] -0.164073827  0.0060121749  0.0

In [195]:
#Solo falta definir una matriz identidad de (20x20)

I <- diag(20)
I

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 1    0    0    0    0    0    0    0    0    0     0     0     0    
 [2,] 0    1    0    0    0    0    0    0    0    0     0     0     0    
 [3,] 0    0    1    0    0    0    0    0    0    0     0     0     0    
 [4,] 0    0    0    1    0    0    0    0    0    0     0     0     0    
 [5,] 0    0    0    0    1    0    0    0    0    0     0     0     0    
 [6,] 0    0    0    0    0    1    0    0    0    0     0     0     0    
 [7,] 0    0    0    0    0    0    1    0    0    0     0     0     0    
 [8,] 0    0    0    0    0    0    0    1    0    0     0     0     0    
 [9,] 0    0    0    0    0    0    0    0    1    0     0     0     0    
[10,] 0    0    0    0    0    0    0    0    0    1     0     0     0    
[11,] 0    0    0    0    0    0    0    0    0    0     1     0     0    
[12,] 0    0    0    0    0    0    0    0    0    0     0     1     0    
[13,] 0    0    0    0    0    0    0    0    0    0     0     0     1    
[14,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
[15,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
[16,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
[17,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
[18,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
[19,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
[20,] 0    0    0    0    0    0    0    0    0    0     0     0     0    
      [,14] [,15] [,16] [,17] [,18] [,19] [,20]
 [1,] 0     0     0     0     0     0     0    
 [2,] 0     0     0     0     0     0     0    
 [3,] 0     0     0     0     0     0     0    
 [4,] 0     0     0     0     0     0     0    
 [5,] 0     0     0     0     0     0     0    
 [6,] 0     0     0     0     0     0     0    
 [7,] 0     0     0     0     0     0     0    
 [8,] 0     0     0     0     0     0     0    
 [9,] 0     0     0     0     0     0     0    
[10,] 0     0     0     0     0     0     0    
[11,] 0     0     0     0     0     0     0    
[12,] 0     0     0     0     0     0     0    
[13,] 0     0     0     0     0     0     0    
[14,] 1     0     0     0     0     0     0    
[15,] 0     1     0     0     0     0     0    
[16,] 0     0     1     0     0     0     0    
[17,] 0     0     0     1     0     0     0    
[18,] 0     0     0     0     1     0     0    
[19,] 0     0     0     0     0     1     0    
[20,] 0     0     0     0     0     0     1

In [199]:
#Finalmente, M = I - H
M <- I-H
M

[,1]         [,2]         [,3]         [,4]         [,5]       
 [1,]  0.649355001 -0.143888071  0.008474908  0.071490248 -0.06708898
 [2,] -0.143888071  0.847325804 -0.039837649  0.107028926 -0.04301009
 [3,]  0.008474908 -0.039837649  0.810164504 -0.140501182 -0.17256999
 [4,]  0.071490248  0.107028926 -0.140501182  0.553815825 -0.06828822
 [5,] -0.067088977 -0.043010087 -0.172569993 -0.068288219  0.76621595
 [6,] -0.158365989 -0.139173010 -0.125734079  0.007317903 -0.12335245
 [7,] -0.058104483 -0.189411484 -0.022774565  0.167987731  0.03704478
 [8,] -0.121529795 -0.109706389 -0.010554013  0.067772029 -0.02511615
 [9,] -0.219422823 -0.038028548  0.037848761 -0.115748558  0.01948002
[10,] -0.104690804  0.008389844  0.108130724 -0.050544109  0.06395661
[11,]  0.187723845 -0.035658586  0.005593478 -0.075565501  0.15005971
[12,] -0.078360163 -0.010030747  0.088106135 -0.133785639  0.13609587
[13,]  0.043006867 -0.026579207 -0.132920559 -0.076413532 -0.13832105
[14,] -0.084349449  0.036864106 -0.060284026 -0.120553196 -0.16190446
[15,] -0.013948699 -0.012783675 -0.079575922 -0.139386138 -0.06562594
[16,] -0.034119595 -0.060001389  0.016225264  0.196165619 -0.10825503
[17,]  0.155766655  0.042985557 -0.006141362 -0.033850971 -0.03131862
[18,] -0.010513971 -0.090431849 -0.037202134  0.077591214 -0.04248236
[19,]  0.085891497 -0.017890143 -0.176009212 -0.196681701 -0.10501395
[20,] -0.107326204 -0.086163404 -0.070439076 -0.097850749 -0.02050565
      [,6]         [,7]         [,8]         [,9]        [,10]        
 [1,] -0.158365989 -0.058104483 -0.121529795 -0.21942282 -0.1046908038
 [2,] -0.139173010 -0.189411484 -0.109706389 -0.03802855  0.0083898442
 [3,] -0.125734079 -0.022774565 -0.010554013  0.03784876  0.1081307243
 [4,]  0.007317903  0.167987731  0.067772029 -0.11574856 -0.0505441091
 [5,] -0.123352454  0.037044775 -0.025116153  0.01948002  0.0639566123
 [6,]  0.801075733 -0.133388761 -0.081083549 -0.03921284  0.0885177967
 [7,] -0.133388761  0.670768101 -0.128070620  0.03246010  0.0489077956
 [8,] -0.081083549 -0.128070620  0.906160272 -0.06290501 -0.0580870443
 [9,] -0.039212839  0.032460100 -0.062905008  0.74586750 -0.1924928883
[10,]  0.088517797  0.048907796 -0.058087044 -0.19249289  0.7090680656
[11,]  0.049849633 -0.220282720 -0.040385375  0.04253720 -0.0519114104
[12,]  0.049099978 -0.030888177 -0.052574224 -0.21115897 -0.2325122584
[13,] -0.058441909 -0.023953924 -0.019729203  0.05544897  0.0376074070
[14,]  0.008639435  0.169241742 -0.010477089 -0.09337680 -0.1375025434
[15,] -0.038640415  0.002193414 -0.020736950 -0.05262749 -0.0403746324
[16,]  0.029338370 -0.041460614 -0.087371369  0.05001646 -0.1314709413
[17,]  0.121082984  0.013808184 -0.014005446  0.06448569 -0.1417510319
[18,] -0.049108529 -0.142576579 -0.077434703  0.03258656 -0.0222566993
[19,] -0.087567702 -0.049099467  0.004292296  0.04597145  0.0984163894
[20,] -0.120852596 -0.102400451 -0.058457667 -0.10172877  0.0005997273
      [,11]        [,12]         [,13]       [,14]         [,15]       
 [1,]  0.187723845 -0.0783601628  0.04300687 -0.0843494489 -0.013948699
 [2,] -0.035658586 -0.0100307471 -0.02657921  0.0368641057 -0.012783675
 [3,]  0.005593478  0.0881061350 -0.13292056 -0.0602840263 -0.079575922
 [4,] -0.075565501 -0.1337856387 -0.07641353 -0.1205531956 -0.139386138
 [5,]  0.150059706  0.1360958744 -0.13832105 -0.1619044566 -0.065625943
 [6,]  0.049849633  0.0490999783 -0.05844191  0.0086394346 -0.038640415
 [7,] -0.220282720 -0.0308881769 -0.02395392  0.1692417425  0.002193414
 [8,] -0.040385375 -0.0525742241 -0.01972920 -0.0104770886 -0.020736950
 [9,]  0.042537196 -0.2111589733  0.05544897 -0.0933767995 -0.052627492
[10,] -0.051911410 -0.2325122584  0.03760741 -0.1375025434 -0.040374632
[11,]  0.534212083 -0.1834736571 -0.03482605  0.1640738269 -0.050997374
[12,] -0.183473657  0.6994317203  0.06567440 -0.0060121749 -0.053986902
[13,] -0.034826051  0.0656744030  0.87118526 -0.0832037921 -0.065128352
[14,]  0.164073827 -0.0060121749 -0.0