1. If statement

In [24]:
import pandas
data= pandas.read_csv (r"C:\Users\USER\Documents\GitHub\1ECO35_R_PYTHON\data\notas.csv")


In [25]:
data['Estado']=["Ingresó"if n>11 else "No ingresó" for n in data['notas']]
data

alumnos   notas carrera      Estado
0       DIEGO     10    a001  No ingresó
1     GABRIEL      4    a001  No ingresó
2       ANDRE      7    a001  No ingresó
3      ANDRES     16    a002     Ingresó
4    FERNANDO     16    a003     Ingresó
5    MILAGROS     19    a002     Ingresó
6       OSCAR      9    a001  No ingresó
7     RODRIGO      1    a003  No ingresó
8   ALEJANDRO      7    a001  No ingresó
9     LORENZO     21    a001     Ingresó
10     ELIANE     18    a001     Ingresó
11     ALDAIR     15    a002     Ingresó
12       LUIS      0    a004  No ingresó
13     JAVIER     12    a001     Ingresó
14     ALONSO     17    a002     Ingresó
15      MARCO     18    a001     Ingresó
16  SEBASTIAN     15    a004     Ingresó
17     LUZCIA      0    a001  No ingresó
18      NAYEL     18    a004     Ingresó
19    JOAQUIN      4    a002  No ingresó
20   ILIZARBE      6    a001  No ingresó
21    VIVIANA     18    a004     Ingresó
22       LUIS     10    a004  No ingresó
23      ROCIO     13    a002     Ingresó
24      LEIDY     21    a001     Ingresó
25    MELISSA     16    a002     Ingresó
26   FERNANDO     15    a001     Ingresó
27     MARTIN     21    a001     Ingresó
28    DANIELA     17    a003     Ingresó
29    GONZALO      7    a001  No ingresó
30      SOFIA      6    a003  No ingresó
31     ANGEL      10    a004  No ingresó
32     CAMILA      1    a001  No ingresó
33      ROSA       3    a001  No ingresó
34    MARCELO     21    a002     Ingresó
35      JOSUE     16    a001     Ingresó
36      RUBEN     19    a002     Ingresó
37       HUGO     13    a003     Ingresó

In [26]:
def Nombre(row):
    if row["carrera"] == "a001":
        return "Economía"
    elif row["carrera"] == "a002":
        return "Química"
    elif row["carrera"] == "a003": 
        return "Filosofía"
    else: 
        return "Otros"

data = data.assign(N_Carrera=data.apply(Nombre,axis=1))
data

alumnos   notas carrera      Estado  N_Carrera
0       DIEGO     10    a001  No ingresó   Economía
1     GABRIEL      4    a001  No ingresó   Economía
2       ANDRE      7    a001  No ingresó   Economía
3      ANDRES     16    a002     Ingresó    Química
4    FERNANDO     16    a003     Ingresó  Filosofía
5    MILAGROS     19    a002     Ingresó    Química
6       OSCAR      9    a001  No ingresó   Economía
7     RODRIGO      1    a003  No ingresó  Filosofía
8   ALEJANDRO      7    a001  No ingresó   Economía
9     LORENZO     21    a001     Ingresó   Economía
10     ELIANE     18    a001     Ingresó   Economía
11     ALDAIR     15    a002     Ingresó    Química
12       LUIS      0    a004  No ingresó      Otros
13     JAVIER     12    a001     Ingresó   Economía
14     ALONSO     17    a002     Ingresó    Química
15      MARCO     18    a001     Ingresó   Economía
16  SEBASTIAN     15    a004     Ingresó      Otros
17     LUZCIA      0    a001  No ingresó   Economía
18      NAYEL     18    a004     Ingresó      Otros
19    JOAQUIN      4    a002  No ingresó    Química
20   ILIZARBE      6    a001  No ingresó   Economía
21    VIVIANA     18    a004     Ingresó      Otros
22       LUIS     10    a004  No ingresó      Otros
23      ROCIO     13    a002     Ingresó    Química
24      LEIDY     21    a001     Ingresó   Economía
25    MELISSA     16    a002     Ingresó    Química
26   FERNANDO     15    a001     Ingresó   Economía
27     MARTIN     21    a001     Ingresó   Economía
28    DANIELA     17    a003     Ingresó  Filosofía
29    GONZALO      7    a001  No ingresó   Economía
30      SOFIA      6    a003  No ingresó  Filosofía
31     ANGEL      10    a004  No ingresó      Otros
32     CAMILA      1    a001  No ingresó   Economía
33      ROSA       3    a001  No ingresó   Economía
34    MARCELO     21    a002     Ingresó    Química
35      JOSUE     16    a001     Ingresó   Economía
36      RUBEN     19    a002     Ingresó    Química
37       HUGO     13    a003     Ingresó  Filosofía

In [ ]:
i = 0

nrows = data.carrera.count()
while i < nrows:
  
    if data['N_Carrera'][i] == "Química" and data['Estado'][i] == "Ingresó": 
        print(data['alumnos'][i])
        i = i +1 

Pregunta 2

Simule un proceso generador de datos con 10 mil observaciones como se explicó en la primera práctica dirigida. Use un loop para obtener los coeficientes estimados con los siguientes tamaños de muestra (10, 50, 100,200,500,1000,5000).

In [1]:
import numpy as np

In [2]:
import random 
random.seed(32154)
muestra= [10,50,100,200,500,1000,5000]
len (muestra)

7

In [4]:
result = []
for i in range(0,7):
    x1 = np.random.rand(muestra[i]) # uniform distribution  [0,1]
    x2 = np.random.rand(muestra[i]) # uniform distribution [0,1]
    x3 = np.random.rand(muestra[i]) # uniform distribution [0,1]
    x4 = np.random.rand(muestra[i]) # uniform distribution [0,1]
    e = np.random.normal(0,1,(muestra[i])) # normal distribution mean = 0 and sd = 1
# Poblacional regression (Data Generating Process GDP)
    Y = 1 + 0.8*x1 + 1.2*x2 + 0.5*x3 + 1.5*x4 + e
    X = np.column_stack((np.ones(muestra[i]), x1,x2,x3,x4))
    beta = np.linalg.inv(X.T @ X) @ ((X.T) @ Y )
    result.append(beta)
    print(beta)

[0.28849633 0.54989549 0.38188926 3.73471304 0.50036191]
[1.91537548 0.45566293 0.95451691 0.00491118 1.31718395]
[1.2587654  0.77267381 1.30497416 0.29350523 1.22542007]
[ 0.91830946  0.72030067  1.93074669 -0.15555686  1.74181711]
[1.18372917 0.68107881 1.17953035 0.44662346 1.27346188]
[1.00028149 0.83904594 1.19301555 0.56789793 1.48826889]
[0.99147754 0.7779359  1.22777034 0.49233837 1.55156003]


...Guardar los coeficientes estimados en un Dataframe. Nombre las columnas del dataframe con los coeficientes estimados (i.e b1, b2, b3 ...) ; y las filas, con el tamaño de muestra (n=10 , n= 50, n= 100, n=200, n=500, n=1000, n= 5000 ).

In [5]:
h = np.vstack(result)
h

array([[ 0.28849633,  0.54989549,  0.38188926,  3.73471304,  0.50036191],
       [ 1.91537548,  0.45566293,  0.95451691,  0.00491118,  1.31718395],
       [ 1.2587654 ,  0.77267381,  1.30497416,  0.29350523,  1.22542007],
       [ 0.91830946,  0.72030067,  1.93074669, -0.15555686,  1.74181711],
       [ 1.18372917,  0.68107881,  1.17953035,  0.44662346,  1.27346188],
       [ 1.00028149,  0.83904594,  1.19301555,  0.56789793,  1.48826889],
       [ 0.99147754,  0.7779359 ,  1.22777034,  0.49233837,  1.55156003]])

In [6]:
row_indices= muestra
row_indices

[10, 50, 100, 200, 500, 1000, 5000]

In [7]:
import pandas as pd
data_df2 = pd.DataFrame(h, index= row_indices, columns=['b1','b2','b3','b4','b5'])
data_df2

b1        b2        b3        b4        b5
10    0.288496  0.549895  0.381889  3.734713  0.500362
50    1.915375  0.455663  0.954517  0.004911  1.317184
100   1.258765  0.772674  1.304974  0.293505  1.225420
200   0.918309  0.720301  1.930747 -0.155557  1.741817
500   1.183729  0.681079  1.179530  0.446623  1.273462
1000  1.000281  0.839046  1.193016  0.567898  1.488269
5000  0.991478  0.777936  1.227770  0.492338  1.551560

Use la base de datos production_fish.csv para obtener el porcentaje de consumo de ciertos tipos de producción marina respecto al consumo de anchoveta. Crear esta información solo para los siguiente tipos producción marina: Atun, Jurel, Langostino, Tollo.

In [8]:
import pandas as pd

datos_productionfish = pd.read_csv (r"..\..\data\production_fish.csv")
datos_productionfish

year    Anchoveta  Concha de abanico  Langostino    Merluza  \
0   2005  8628.396000          13.537000    9.021000  23.279000   
1   2006  5891.838000          14.714000   11.295000  25.189000   
2   2007  6084.713000          19.937000   13.548000  28.358488   
3   2008  6159.387000          18.790000   12.817000  26.348398   
4   2009  5828.636000          24.634372   11.877399  36.774763   
5   2010  3330.413040          60.001250   14.477939  25.647697   
6   2011  7000.092781          92.027637   23.384478  28.544458   
7   2012  3693.871080          38.933390   22.707220  21.054780   
8   2013  4754.118210          89.293284   19.111372  31.187461   
9   2014  2255.453460          52.266500   21.762990  30.770800   
10  2015  3616.481500          14.843150   26.772210  25.644130   
11  2016  2732.733740          10.090130   29.253750  25.800210   
12  2017  3165.490240           4.596090   38.760070  37.147430   
13  2018  6072.887839          36.530349   31.505879  34.876576   
14  2019  3381.437222          53.112863   42.857637  28.979849   
15  2020  4314.558220          46.995287   34.516971  19.842900   

    Calamar gigante       Atun    Caballa       Jurel   Sardina  \
0        235.630000   9.877000  25.711000   20.481000  0.165000   
1        365.729000  11.336000  58.245000  122.904000  0.048000   
2        379.556594   3.713293  26.248739   82.910307  0.001020   
3        484.162082   3.283711  47.694121   58.864202  0.000000   
4        355.106589   2.017061  51.355908   14.289041  0.000000   
5        327.571909   9.182845   9.729522    5.774274  0.000000   
6        373.195661   6.586856  20.478814   83.277943  0.054463   
7        457.072670   1.115060   9.978510   43.693940  0.088460   
8        410.759534   7.136436  26.600553    7.197624  0.000000   
9        465.007580   4.734540  29.576440    8.882560  0.000000   
10       426.932300  11.082120  15.314910    2.769796  0.164140   
11       246.124700  10.884490  57.675170    0.412040  0.007490   
12       252.429930  11.802750  23.249140    1.052910  0.000000   
13       319.146488  18.138975  24.610468   14.619846  0.000000   
14       483.765239  17.839298  19.598784   27.733432  0.000000   
15       407.384850   3.843680  28.408700   23.475890  0.000000   

    Concha de abanico.1     Jurel.1       Liza     Tollo  total_production  
0              1.843080   56.167940   5.875600  0.430000       9030.413620  
1              4.048000  136.827000   3.166000  1.584000       6646.923000  
2              4.822991  134.887316   9.317622  2.834958       6790.849328  
3              0.828187   80.092885  14.514054  2.933360       6909.715000  
4              1.843072   47.079175  17.311344  4.057886       6394.982610  
5              2.824749   10.404933   9.706363  4.994712       3810.729233  
6              0.873130   72.955117  12.124808  5.687520       7719.283666  
7              0.744610   72.930470  17.162420  4.235380       4383.587990  
8              2.180252   54.454541  12.530821  3.945647       5418.515737  
9              0.608160   46.346459  12.248670  5.206880       2932.865039  
10             0.615910   17.536930  12.463520  7.717680       4178.338296  
11             0.579750   12.472050  15.757580  9.453130       3151.244230  
12             0.373700    6.889530  29.061740  6.692660       3577.546190  
13             1.551366   14.720969  23.326310  3.672117       6595.587183  
14             1.226521   40.798701  24.029820  1.241883       4122.621249  
15             0.616697   48.115810  14.992172  0.544585       4943.295762

In [9]:
datos_productionfish['Atun_%']   = (datos_productionfish['Atun']   / datos_productionfish['Anchoveta']) * 100
datos_productionfish['Jurel_%'] = (datos_productionfish['Jurel'] / datos_productionfish['Anchoveta']) * 100
datos_productionfish['Langostino_%'] = (datos_productionfish['Langostino'] / datos_productionfish['Anchoveta']) * 100
datos_productionfish['Tollo_%']  = (datos_productionfish['Tollo']  /datos_productionfish['Anchoveta']) * 100
datos_productionfish.round(2)

datos_productionfish

year    Anchoveta  Concha de abanico  Langostino    Merluza  \
0   2005  8628.396000          13.537000    9.021000  23.279000   
1   2006  5891.838000          14.714000   11.295000  25.189000   
2   2007  6084.713000          19.937000   13.548000  28.358488   
3   2008  6159.387000          18.790000   12.817000  26.348398   
4   2009  5828.636000          24.634372   11.877399  36.774763   
5   2010  3330.413040          60.001250   14.477939  25.647697   
6   2011  7000.092781          92.027637   23.384478  28.544458   
7   2012  3693.871080          38.933390   22.707220  21.054780   
8   2013  4754.118210          89.293284   19.111372  31.187461   
9   2014  2255.453460          52.266500   21.762990  30.770800   
10  2015  3616.481500          14.843150   26.772210  25.644130   
11  2016  2732.733740          10.090130   29.253750  25.800210   
12  2017  3165.490240           4.596090   38.760070  37.147430   
13  2018  6072.887839          36.530349   31.505879  34.876576   
14  2019  3381.437222          53.112863   42.857637  28.979849   
15  2020  4314.558220          46.995287   34.516971  19.842900   

    Calamar gigante       Atun    Caballa       Jurel   Sardina  \
0        235.630000   9.877000  25.711000   20.481000  0.165000   
1        365.729000  11.336000  58.245000  122.904000  0.048000   
2        379.556594   3.713293  26.248739   82.910307  0.001020   
3        484.162082   3.283711  47.694121   58.864202  0.000000   
4        355.106589   2.017061  51.355908   14.289041  0.000000   
5        327.571909   9.182845   9.729522    5.774274  0.000000   
6        373.195661   6.586856  20.478814   83.277943  0.054463   
7        457.072670   1.115060   9.978510   43.693940  0.088460   
8        410.759534   7.136436  26.600553    7.197624  0.000000   
9        465.007580   4.734540  29.576440    8.882560  0.000000   
10       426.932300  11.082120  15.314910    2.769796  0.164140   
11       246.124700  10.884490  57.675170    0.412040  0.007490   
12       252.429930  11.802750  23.249140    1.052910  0.000000   
13       319.146488  18.138975  24.610468   14.619846  0.000000   
14       483.765239  17.839298  19.598784   27.733432  0.000000   
15       407.384850   3.843680  28.408700   23.475890  0.000000   

    Concha de abanico.1     Jurel.1       Liza     Tollo  total_production  \
0              1.843080   56.167940   5.875600  0.430000       9030.413620   
1              4.048000  136.827000   3.166000  1.584000       6646.923000   
2              4.822991  134.887316   9.317622  2.834958       6790.849328   
3              0.828187   80.092885  14.514054  2.933360       6909.715000   
4              1.843072   47.079175  17.311344  4.057886       6394.982610   
5              2.824749   10.404933   9.706363  4.994712       3810.729233   
6              0.873130   72.955117  12.124808  5.687520       7719.283666   
7              0.744610   72.930470  17.162420  4.235380       4383.587990   
8              2.180252   54.454541  12.530821  3.945647       5418.515737   
9              0.608160   46.346459  12.248670  5.206880       2932.865039   
10             0.615910   17.536930  12.463520  7.717680       4178.338296   
11             0.579750   12.472050  15.757580  9.453130       3151.244230   
12             0.373700    6.889530  29.061740  6.692660       3577.546190   
13             1.551366   14.720969  23.326310  3.672117       6595.587183   
14             1.226521   40.798701  24.029820  1.241883       4122.621249   
15             0.616697   48.115810  14.992172  0.544585       4943.295762   

      Atun_%   Jurel_%  Langostino_%   Tollo_%  
0   0.114471  0.237367      0.104550  0.004984  
1   0.192402  2.086004      0.191706  0.026885  
2   0.061027  1.362600      0.222656  0.046591  
3   0.053312  0.955683      0.208089  0.047624  
4   0.034606  0.245152      0.203777  0.069620  
5   0.275727  0.173380      0.434719  0.149973  
6   0.094097  1.189669      0.334060  0.081249  
7   0

Ejercicio solo en Python: Usar la base de datos places result para crear un DataFrame con la siguiente información: nombre de la institución pública, dirección (formatted_address), situación de actividad (business_status) y las coordenadas correspondientes a northeast y southwest.

In [11]:
from tqdm import tqdm   #measure time
import pickle  
import pandas as pd #para trabajar con data frame

In [12]:
dictionary_places = open("..\..\data\places_result", "rb")
places_result = pickle.load( dictionary_places )

In [13]:
places_result.keys()

dict_keys(['html_attributions', 'next_page_token', 'results', 'status'])

In [14]:
places_result['results']

[{'business_status': 'OPERATIONAL',
  'formatted_address': '11 Sokode Crescent, Off Dalaba Street Zone 5, Wuse P. M. B, 18, Garki, Abuja',
  'geometry': {'location': {'lat': 9.065977, 'lng': 7.4549606},
   'viewport': {'northeast': {'lat': 9.067332429892723,
     'lng': 7.456282779892721},
    'southwest': {'lat': 9.064632770107277, 'lng': 7.453583120107277}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
  'name': 'National Identity Management Commission',
  'opening_hours': {'open_now': False},
  'photos': [{'height': 1080,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/110095172826797559117">Fortune Arinze</a>'],
    'photo_reference': 'ATtYBwIfz2h2rM_FJkG-yQBlkVWKeovt6ifUcEMS-oibn4T5zgXhLpqhrl1lj07-RfAhWjrwClBoAgc_3Ckh-TekOWbaaQu-0J03OHYQBMqZK6xYSOonfP3tABNHcj_--1XB6urnlYHXNenRO8RhLJC9ahW3AjPS3t2Z4Ssh9hV-hQ-VjJuy',
    'width': 1920}],
  'place_id': 'ChIJwRTVOSELThARczd6MyuWUbs',
  'plus_code': {'compound

In [15]:
resultados = places_result[ 'results' ]

In [16]:
# para extraer las listas que queremos

instituciones = []
direccion = []
actividad = []
northeast = []
southwest = []

# loop para guardar cada uno de los elementos
for row in tqdm( range( 0 , len( resultados ) ) ):
    
    # direccion
    dire = resultados[ row ]['formatted_address']
    
    # estado de la actividad
    act = resultados[ row ]['business_status']
    
    # nombre de la institution
    institution = resultados[ row ]['name']
    
    # southwest
    south= resultados[ row ]['geometry']['viewport']['southwest']
    
    # northwest
    north = resultados[ row ]['geometry']['viewport']['northeast']
    
     # Save results
    instituciones.append( institution )
    direccion.append( dire )
    actividad.append( act )
    northeast.append( north )
    southwest.append( south )

100%|██████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<?, ?it/s]


In [17]:
# Diccionario
resultado_final = { 'Institucion': instituciones, 'Estado' : actividad,'Direccion' : direccion, 'Direccion_norte' : northeast, 'Direccion_sur' : southwest }
# Dataframe
dataframe = pd.DataFrame( resultado_final )
dataframe

Institucion       Estado  \
0             National Identity Management Commission  OPERATIONAL   
1        National Identity Management Commission NIMC  OPERATIONAL   
2      National Identity Management Commission (Nimc)  OPERATIONAL   
3             National Identity Management Commission  OPERATIONAL   
4      National Identity Management Commission (Nimc)  OPERATIONAL   
5             National Identity Management Commission  OPERATIONAL   
6             National Identity Management Commission  OPERATIONAL   
7      National Identity Management Commission (Nimc)  OPERATIONAL   
8      National Identity Management Commission (Nimc)  OPERATIONAL   
9             National Identity Management Commission  OPERATIONAL   
10     National Identity Management Commission (Nimc)  OPERATIONAL   
11                National Identity Management Center  OPERATIONAL   
12     National Identity Management Commission (Nimc)  OPERATIONAL   
13  National Identity Management Commision (NIMC) ...  OPERATIONAL   
14            National Identity Management Commission  OPERATIONAL   
15  National Identity Management Commission, North...  OPERATIONAL   
16     National Identity Management Commission (Nimc)  OPERATIONAL   
17    National Identity Management Commission Umuahia  OPERATIONAL   
18            National Identity Management Commission  OPERATIONAL   
19       National Identity Management Commission Nimc  OPERATIONAL   

                                            Direccion  \
0   11 Sokode Crescent, Off Dalaba Street Zone 5, ...   
1                           Lafia - Shandam Rd, Lafia   
2        Asa-Dam Rd, opp. Dangote Flour Mills, Ilorin   
3                 zone 3, No 4 Maputo St, Wuse, Abuja   
4                            Lamingo Dam Road Plateau   
5                                                 Jos   
6                                              Kachia   
7                Jonah Jang Cres, High Level, Makurdi   
8        3 Abdulkadir ahmed Close (P.M.B 0281, Bauchi   
9                                  Kofar Kabuga, Kano   
10         Complex, Federal Secretariat, Kawo, Kaduna   
11                Port-Hacourt Rd, New Owerri, Owerri   
12  ITF House, 6, 3rd Floor, Adetokunbo Ademola Cr...   
13            9 Obafemi Awolowo Way, Agidingbi, Ikeja   
14  1 Proda Road,Proda Junction, Emene industrial ...   
15                 Bayajida Rd, Ungwan Munchi, Kaduna   
16                         Tal-Udu, FCE Junction Kano   
17                                Ndume bypass, Ndume   
18                              Umueme, Port Harcourt   
19  238 Port Harcourt - Aba Expy, Rumuokwurusi, Po...   

                                      Direccion_norte  \
0   {'lat': 9.067332429892723, 'lng': 7.4562827798...   
1   {'lat': 8.506788579892724, 'lng': 8.5332722298...   
2   {'lat': 8.451072679892722, 'lng': 4.5437053298...   
3   {'lat': 9.06035997989272, 'lng': 7.46923637989...   
4                {'lat': 9.8984195, 'lng': 8.9328039}   
5   {'lat': 9.893702729892722, 'lng': 8.9188880798...   
6   {'lat': 9.858620379892722, 'lng': 7.9693469298...   
7   {'lat': 7.712382379892722, 'lng': 8.5282094298...   
8   {'lat': 10.31170367989272, 'lng': 9.8279278798...   
9   {'lat': 11.99139672989272, 'lng': 8.4903341298...   
10  {'lat': 10.59382137989272, 'lng': 7.4508104298...   
11  {'lat': 5.473014629892722, 'lng': 7.0094772798...   
12  {'lat': 9.078071879892722, 'lng': 7.4952152298...   
13  {'lat': 6.618298179892721, 'lng': 3.3595877798...   
14  {'lat': 6.461432879892723, 'lng': 7.5803212798...   
15  {'lat': 10.54495552989272, 'lng': 7.4623366798...   
16  {'lat': 11.98937482989272, 'lng': 8.4981432298...   
17  {'lat': 5.503745479892721, 'lng': 7.5191573798...   
18  {'lat': 4.823459929892723, 'lng': 7.0092882798...   
19  {'lat': 4.850934679892722, 'lng': 7.0540891798...   

                                        Direccion_sur  
0   {'lat': 9.064632770107277, 'lng': 7.4535831201...  
1   {'lat': 8.50408892010728, 'lng': 8.53057257010...  
2   {'l

Pregunta 3

Crear una matrix aleatoria de orden 100x10. Crear un función que permita estandariza cada columna; es decir, cada observación de una columna debe restarse por su media y dividirse por la desviación estándar de la columna. Llame a esta función como standarize

In [18]:
# import module
import numpy as np
array = np.arange(1000) - 8
matrix = array.reshape(100, 10)  
print("Matriz 100*10 \n", matrix)

Matriz 100*10 
 [[ -8  -7  -6  -5  -4  -3  -2  -1   0   1]
 [  2   3   4   5   6   7   8   9  10  11]
 [ 12  13  14  15  16  17  18  19  20  21]
 [ 22  23  24  25  26  27  28  29  30  31]
 [ 32  33  34  35  36  37  38  39  40  41]
 [ 42  43  44  45  46  47  48  49  50  51]
 [ 52  53  54  55  56  57  58  59  60  61]
 [ 62  63  64  65  66  67  68  69  70  71]
 [ 72  73  74  75  76  77  78  79  80  81]
 [ 82  83  84  85  86  87  88  89  90  91]
 [ 92  93  94  95  96  97  98  99 100 101]
 [102 103 104 105 106 107 108 109 110 111]
 [112 113 114 115 116 117 118 119 120 121]
 [122 123 124 125 126 127 128 129 130 131]
 [132 133 134 135 136 137 138 139 140 141]
 [142 143 144 145 146 147 148 149 150 151]
 [152 153 154 155 156 157 158 159 160 161]
 [162 163 164 165 166 167 168 169 170 171]
 [172 173 174 175 176 177 178 179 180 181]
 [182 183 184 185 186 187 188 189 190 191]
 [192 193 194 195 196 197 198 199 200 201]
 [202 203 204 205 206 207 208 209 210 211]
 [212 213 214 215 216 217 218 219 220 

In [19]:
def standarize(matrix):
    norm = np.linalg.norm(matrix, 1)
    # normalized matrix
    matrix = matrix/norm  
    return matrix

In [20]:
standarize_matrix = standarize(matrix)

In [21]:
print("\nMatriz estandarizada \n", standarize_matrix)


Matriz estandarizada 
 [[-1.61290323e-04 -1.41129032e-04 -1.20967742e-04 -1.00806452e-04
  -8.06451613e-05 -6.04838710e-05 -4.03225806e-05 -2.01612903e-05
   0.00000000e+00  2.01612903e-05]
 [ 4.03225806e-05  6.04838710e-05  8.06451613e-05  1.00806452e-04
   1.20967742e-04  1.41129032e-04  1.61290323e-04  1.81451613e-04
   2.01612903e-04  2.21774194e-04]
 [ 2.41935484e-04  2.62096774e-04  2.82258065e-04  3.02419355e-04
   3.22580645e-04  3.42741935e-04  3.62903226e-04  3.83064516e-04
   4.03225806e-04  4.23387097e-04]
 [ 4.43548387e-04  4.63709677e-04  4.83870968e-04  5.04032258e-04
   5.24193548e-04  5.44354839e-04  5.64516129e-04  5.84677419e-04
   6.04838710e-04  6.25000000e-04]
 [ 6.45161290e-04  6.65322581e-04  6.85483871e-04  7.05645161e-04
   7.25806452e-04  7.45967742e-04  7.66129032e-04  7.86290323e-04
   8.06451613e-04  8.26612903e-04]
 [ 8.46774194e-04  8.66935484e-04  8.87096774e-04  9.07258065e-04
   9.27419355e-04  9.47580645e-04  9.67741935e-04  9.87903226e-04
   1.0080