# WORKGROUP 2 PYTHON


In [54]:
from IPython.display import display, HTML

display(HTML(data="""
<style>
    div#notebook-container    { width: 90%; }
    div#menubar-container     { width: 90%; }
    div#maintoolbar-container { width: 99%; }a
</style>
"""))


# 1.If statement:

- Un archivo .csv llamado notas está en la carpeta data. Esta base de datos posee información de algunos postulantes universitarios a la universidad. Use if statement para crear una nueva columna e indicar si el el alumno ingreso o no (nota minima aprobatoria es 11)

In [6]:
import pandas as pd

data = pd.read_csv (r'C:\Users\maria\OneDrive\Documentos\GitHub\R-y-Python\notas.csv')   
print (data)

     alumnos   notas carrera
0       DIEGO     10    a001
1     GABRIEL      4    a001
2       ANDRE      7    a001
3      ANDRES     16    a002
4    FERNANDO     16    a003
5    MILAGROS     19    a002
6       OSCAR      9    a001
7     RODRIGO      1    a003
8   ALEJANDRO      7    a001
9     LORENZO     21    a001
10     ELIANE     18    a001
11     ALDAIR     15    a002
12       LUIS      0    a004
13     JAVIER     12    a001
14     ALONSO     17    a002
15      MARCO     18    a001
16  SEBASTIAN     15    a004
17     LUZCIA      0    a001
18      NAYEL     18    a004
19    JOAQUIN      4    a002
20   ILIZARBE      6    a001
21    VIVIANA     18    a004
22       LUIS     10    a004
23      ROCIO     13    a002
24      LEIDY     21    a001
25    MELISSA     16    a002
26   FERNANDO     15    a001
27     MARTIN     21    a001
28    DANIELA     17    a003
29    GONZALO      7    a001
30      SOFIA      6    a003
31     ANGEL      10    a004
32     CAMILA      1    a001
33      ROSA  

In [7]:
data['resultados'] = ["aprobado" if  s>=11 else "desaprobado" for s in data['notas']]
print(data)

     alumnos   notas carrera   resultados
0       DIEGO     10    a001  desaprobado
1     GABRIEL      4    a001  desaprobado
2       ANDRE      7    a001  desaprobado
3      ANDRES     16    a002     aprobado
4    FERNANDO     16    a003     aprobado
5    MILAGROS     19    a002     aprobado
6       OSCAR      9    a001  desaprobado
7     RODRIGO      1    a003  desaprobado
8   ALEJANDRO      7    a001  desaprobado
9     LORENZO     21    a001     aprobado
10     ELIANE     18    a001     aprobado
11     ALDAIR     15    a002     aprobado
12       LUIS      0    a004  desaprobado
13     JAVIER     12    a001     aprobado
14     ALONSO     17    a002     aprobado
15      MARCO     18    a001     aprobado
16  SEBASTIAN     15    a004     aprobado
17     LUZCIA      0    a001  desaprobado
18      NAYEL     18    a004     aprobado
19    JOAQUIN      4    a002  desaprobado
20   ILIZARBE      6    a001  desaprobado
21    VIVIANA     18    a004     aprobado
22       LUIS     10    a004  desa

- Luego crear un columna para colocar el nombre completo de la carrera a la que postulo el alumno (a001 : Economia, a002: quimica, a003: filosofia).

In [96]:
def carrera_nombre(row):
    if row["carrera"] == "a001":
        return "economia"
    elif row["carrera"] == "a002":
        return "quimica"
    elif row["carrera"] == "a003":
        return "filosofia"
    else:
        return "psicologia"

data = data.assign(nombre=data.apply(carrera_nombre, axis=1))

print(data)

     alumnos   notas carrera   resultados      nombre
0       DIEGO     10    a001  desaprobado    economia
1     GABRIEL      4    a001  desaprobado    economia
2       ANDRE      7    a001  desaprobado    economia
3      ANDRES     16    a002     aprobado     quimica
4    FERNANDO     16    a003     aprobado   filosofia
5    MILAGROS     19    a002     aprobado     quimica
6       OSCAR      9    a001  desaprobado    economia
7     RODRIGO      1    a003  desaprobado   filosofia
8   ALEJANDRO      7    a001  desaprobado    economia
9     LORENZO     21    a001     aprobado    economia
10     ELIANE     18    a001     aprobado    economia
11     ALDAIR     15    a002     aprobado     quimica
12       LUIS      0    a004  desaprobado  psicologia
13     JAVIER     12    a001     aprobado    economia
14     ALONSO     17    a002     aprobado     quimica
15      MARCO     18    a001     aprobado    economia
16  SEBASTIAN     15    a004     aprobado  psicologia
17     LUZCIA      0    a001

- Use un loop while para mostrar el nombre de las personas ingresantes a la carrera de quimica.

In [8]:
i = 0

# row by row
nrows = data.carrera.count()
while i < nrows:
  
    if data['carrera'][i] == "a002" and data['resultados'][i] == "aprobado": 
        print(data['alumnos '][i])
        i = i +1
        
    else: 
        i = i +1   

ANDRES
MILAGROS
ALDAIR
ALONSO
ROCIO
MELISSA
MARCELO
RUBEN


## 2. loops:

- Simule un proceso generador de datos con 10 mil observaciones como se explicó en la primera práctica dirigida. Use un loop para obtener los coeficientes estimados con los siguientes tamaños de muestra (10, 50, 100,200,500,1000,5000).

In [17]:
import numpy as np

In [42]:
import random 
random.seed(10000)
muestra= [10,50,100,200,500,1000,5000]
len (muestra)

7

In [45]:
result = []
for i in range(0,7):
    x1 = np.random.rand(muestra[i]) # uniform distribution  [0,1]
    x2 = np.random.rand(muestra[i]) # uniform distribution [0,1]
    e = np.random.normal(0,1,(muestra[i])) # normal distribution mean = 0 and sd = 1
# Poblacional regression (Data Generating Process GDP)
    Y = 2 + 3*x1 + 4*x2 + e
    X = np.column_stack((np.ones(muestra[i]), x1,x2))
    beta = np.linalg.inv(X.T @ X) @ ((X.T) @ Y )
    result.append(beta)
    print(beta)

[2.22006337 2.52330635 3.9731782 ]
[2.11564672 3.260135   3.15944498]
[1.94263698 3.18717207 4.31854024]
[1.84557942 3.45023641 4.13032807]
[1.95995713 2.78858213 4.18499017]
[1.97964009 2.96938294 4.0894617 ]
[2.04326058 2.97650729 3.92017068]


- Guardar los coeficientes estimados en un Dataframe. Nombre las columnas del dataframe con los coeficientes estimados (i.e b1, b2, b3 ...) ; y las filas, con el tamaño de muestra (n=10 , n= 50, ... ).

In [46]:
h = np.vstack(result)
h

array([[2.22006337, 2.52330635, 3.9731782 ],
       [2.11564672, 3.260135  , 3.15944498],
       [1.94263698, 3.18717207, 4.31854024],
       [1.84557942, 3.45023641, 4.13032807],
       [1.95995713, 2.78858213, 4.18499017],
       [1.97964009, 2.96938294, 4.0894617 ],
       [2.04326058, 2.97650729, 3.92017068]])

In [50]:
row_indices= muestra
row_indices

[10, 50, 100, 200, 500, 1000, 5000]

In [49]:
data_df2 = pd.DataFrame(j, index= row_indices, columns=['b1','b2','b3'])
data_df2

b1        b2        b3
10    1.379506  3.527792  4.200616
50    2.028523  2.382510  4.463857
100   2.350243  3.307583  3.247890
200   1.977537  3.103108  4.084158
500   1.972815  2.832264  4.229308
1000  1.831554  3.065124  4.140272
5000  1.997215  2.982288  4.022706

- Use la base de datos production_fish.csv para obtener el porcentaje de consumo de ciertos tipos de producción marina respecto al consumo de anchoveta. Crear esta información solo para los siguiente tipos producción marina: Atun, Jurel, Langostino, Tollo.

In [52]:
import pandas as pd

datos_productionfish = pd.read_csv (r'C:\Users\maria\OneDrive\Documentos\GitHub\1ECO35_R_PYTHON\data\production_fish.csv')
datos_productionfish

year    Anchoveta  Concha de abanico  Langostino    Merluza  \
0   2005  8628.396000          13.537000    9.021000  23.279000   
1   2006  5891.838000          14.714000   11.295000  25.189000   
2   2007  6084.713000          19.937000   13.548000  28.358488   
3   2008  6159.387000          18.790000   12.817000  26.348398   
4   2009  5828.636000          24.634372   11.877399  36.774763   
5   2010  3330.413040          60.001250   14.477939  25.647697   
6   2011  7000.092781          92.027637   23.384478  28.544458   
7   2012  3693.871080          38.933390   22.707220  21.054780   
8   2013  4754.118210          89.293284   19.111372  31.187461   
9   2014  2255.453460          52.266500   21.762990  30.770800   
10  2015  3616.481500          14.843150   26.772210  25.644130   
11  2016  2732.733740          10.090130   29.253750  25.800210   
12  2017  3165.490240           4.596090   38.760070  37.147430   
13  2018  6072.887839          36.530349   31.505879  34.876576   
14  2019  3381.437222          53.112863   42.857637  28.979849   
15  2020  4314.558220          46.995287   34.516971  19.842900   

    Calamar gigante       Atun    Caballa       Jurel   Sardina  \
0        235.630000   9.877000  25.711000   20.481000  0.165000   
1        365.729000  11.336000  58.245000  122.904000  0.048000   
2        379.556594   3.713293  26.248739   82.910307  0.001020   
3        484.162082   3.283711  47.694121   58.864202  0.000000   
4        355.106589   2.017061  51.355908   14.289041  0.000000   
5        327.571909   9.182845   9.729522    5.774274  0.000000   
6        373.195661   6.586856  20.478814   83.277943  0.054463   
7        457.072670   1.115060   9.978510   43.693940  0.088460   
8        410.759534   7.136436  26.600553    7.197624  0.000000   
9        465.007580   4.734540  29.576440    8.882560  0.000000   
10       426.932300  11.082120  15.314910    2.769796  0.164140   
11       246.124700  10.884490  57.675170    0.412040  0.007490   
12       252.429930  11.802750  23.249140    1.052910  0.000000   
13       319.146488  18.138975  24.610468   14.619846  0.000000   
14       483.765239  17.839298  19.598784   27.733432  0.000000   
15       407.384850   3.843680  28.408700   23.475890  0.000000   

    Concha de abanico.1     Jurel.1       Liza     Tollo  total_production  
0              1.843080   56.167940   5.875600  0.430000       9030.413620  
1              4.048000  136.827000   3.166000  1.584000       6646.923000  
2              4.822991  134.887316   9.317622  2.834958       6790.849328  
3              0.828187   80.092885  14.514054  2.933360       6909.715000  
4              1.843072   47.079175  17.311344  4.057886       6394.982610  
5              2.824749   10.404933   9.706363  4.994712       3810.729233  
6              0.873130   72.955117  12.124808  5.687520       7719.283666  
7              0.744610   72.930470  17.162420  4.235380       4383.587990  
8              2.180252   54.454541  12.530821  3.945647       5418.515737  
9              0.608160   46.346459  12.248670  5.206880       2932.865039  
10             0.615910   17.536930  12.463520  7.717680       4178.338296  
11             0.579750   12.472050  15.757580  9.453130       3151.244230  
12             0.373700    6.889530  29.061740  6.692660       3577.546190  
13             1.551366   14.720969  23.326310  3.672117       6595.587183  
14             1.226521   40.798701  24.029820  1.241883       4122.621249  
15             0.616697   48.115810  14.992172  0.544585       4943.295762

In [53]:
datos_productionfish['Atun_percent']   = (datos_productionfish['Atun']   / datos_productionfish['Anchoveta'].sum()) * 100
datos_productionfish['Jurel_percent'] = (datos_productionfish['Jurel'] / datos_productionfish['Anchoveta'].sum()) * 100
datos_productionfish['Langostino_percent'] = (datos_productionfish['Langostino'] / datos_productionfish['Anchoveta'].sum()) * 100
datos_productionfish['Tollo_percent']  = (datos_productionfish['Tollo']  /datos_productionfish['Anchoveta'].sum()) * 100
datos_productionfish.round(2)

datos_productionfish

year    Anchoveta  Concha de abanico  Langostino    Merluza  \
0   2005  8628.396000          13.537000    9.021000  23.279000   
1   2006  5891.838000          14.714000   11.295000  25.189000   
2   2007  6084.713000          19.937000   13.548000  28.358488   
3   2008  6159.387000          18.790000   12.817000  26.348398   
4   2009  5828.636000          24.634372   11.877399  36.774763   
5   2010  3330.413040          60.001250   14.477939  25.647697   
6   2011  7000.092781          92.027637   23.384478  28.544458   
7   2012  3693.871080          38.933390   22.707220  21.054780   
8   2013  4754.118210          89.293284   19.111372  31.187461   
9   2014  2255.453460          52.266500   21.762990  30.770800   
10  2015  3616.481500          14.843150   26.772210  25.644130   
11  2016  2732.733740          10.090130   29.253750  25.800210   
12  2017  3165.490240           4.596090   38.760070  37.147430   
13  2018  6072.887839          36.530349   31.505879  34.876576   
14  2019  3381.437222          53.112863   42.857637  28.979849   
15  2020  4314.558220          46.995287   34.516971  19.842900   

    Calamar gigante       Atun    Caballa       Jurel   Sardina  \
0        235.630000   9.877000  25.711000   20.481000  0.165000   
1        365.729000  11.336000  58.245000  122.904000  0.048000   
2        379.556594   3.713293  26.248739   82.910307  0.001020   
3        484.162082   3.283711  47.694121   58.864202  0.000000   
4        355.106589   2.017061  51.355908   14.289041  0.000000   
5        327.571909   9.182845   9.729522    5.774274  0.000000   
6        373.195661   6.586856  20.478814   83.277943  0.054463   
7        457.072670   1.115060   9.978510   43.693940  0.088460   
8        410.759534   7.136436  26.600553    7.197624  0.000000   
9        465.007580   4.734540  29.576440    8.882560  0.000000   
10       426.932300  11.082120  15.314910    2.769796  0.164140   
11       246.124700  10.884490  57.675170    0.412040  0.007490   
12       252.429930  11.802750  23.249140    1.052910  0.000000   
13       319.146488  18.138975  24.610468   14.619846  0.000000   
14       483.765239  17.839298  19.598784   27.733432  0.000000   
15       407.384850   3.843680  28.408700   23.475890  0.000000   

    Concha de abanico.1     Jurel.1       Liza     Tollo  total_production  \
0              1.843080   56.167940   5.875600  0.430000       9030.413620   
1              4.048000  136.827000   3.166000  1.584000       6646.923000   
2              4.822991  134.887316   9.317622  2.834958       6790.849328   
3              0.828187   80.092885  14.514054  2.933360       6909.715000   
4              1.843072   47.079175  17.311344  4.057886       6394.982610   
5              2.824749   10.404933   9.706363  4.994712       3810.729233   
6              0.873130   72.955117  12.124808  5.687520       7719.283666   
7              0.744610   72.930470  17.162420  4.235380       4383.587990   
8              2.180252   54.454541  12.530821  3.945647       5418.515737   
9              0.608160   46.346459  12.248670  5.206880       2932.865039   
10             0.615910   17.536930  12.463520  7.717680       4178.338296   
11             0.579750   12.472050  15.757580  9.453130       3151.244230   
12             0.373700    6.889530  29.061740  6.692660       3577.546190   
13             1.551366   14.720969  23.326310  3.672117       6595.587183   
14             1.226521   40.798701  24.029820  1.241883       4122.621249   
15             0.616697   48.115810  14.992172  0.544585       4943.295762   

    Atun_percent  Jurel_percent  Langostino_percent  Tollo_percent  
0       0.012842       0.026630            0.011729       0.000559  
1       0.014739       0.159801            0.014686       0.002060  
2       0.004828       0.107801            0.017615       0.003686  
3       0.004270       0.076536            0.016665       0.003814  
4       0.002623       0.018579            0.015443 

- Ejercicio solo en Python: Usar la base de datos places result para crear un DataFrame con la siguiente información: nombre de la institución pública, dirección (formatted_address), situación de actividad (business_status) y las coordenadas correspondientes a northeast y southwest.

In [55]:
from tqdm import tqdm   #measure time
import pickle  
import pandas as pd #para trabajar con data frame

In [89]:
dictionary_places = open("places_result", "rb")
places_result = pickle.load( dictionary_places )

In [90]:
places_result.keys()

dict_keys(['html_attributions', 'next_page_token', 'results', 'status'])

In [91]:
places_result['results']

[{'business_status': 'OPERATIONAL',
  'formatted_address': '11 Sokode Crescent, Off Dalaba Street Zone 5, Wuse P. M. B, 18, Garki, Abuja',
  'geometry': {'location': {'lat': 9.065977, 'lng': 7.4549606},
   'viewport': {'northeast': {'lat': 9.067332429892723,
     'lng': 7.456282779892721},
    'southwest': {'lat': 9.064632770107277, 'lng': 7.453583120107277}}},
  'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
  'name': 'National Identity Management Commission',
  'opening_hours': {'open_now': False},
  'photos': [{'height': 1080,
    'html_attributions': ['<a href="https://maps.google.com/maps/contrib/110095172826797559117">Fortune Arinze</a>'],
    'photo_reference': 'ATtYBwIfz2h2rM_FJkG-yQBlkVWKeovt6ifUcEMS-oibn4T5zgXhLpqhrl1lj07-RfAhWjrwClBoAgc_3Ckh-TekOWbaaQu-0J03OHYQBMqZK6xYSOonfP3tABNHcj_--1XB6urnlYHXNenRO8RhLJC9ahW3AjPS3t2Z4Ssh9hV-hQ-VjJuy',
    'width': 1920}],
  'place_id': 'ChIJwRTVOSELThARczd6MyuWUbs',
  'plus_code': {'compound

In [94]:
resultados = places_result[ 'results' ]

In [95]:
# para extraer las listas que queremos 

instituciones = []
direccion = []
actividad = []
northeast = []
southwest = []

# loop para guardar cada uno de los elementos
for row in tqdm( range( 0 , len( resultados ) ) ):
    
    # direccion
    dire = resultados[ row ]['formatted_address']
    
    # estado de la actividad
    act = resultados[ row ]['business_status']
    
    # nombre de la institution
    institution = resultados[ row ]['name']
    
    # southwest
    south= resultados[ row ]['geometry']['viewport']['southwest']
    
    # northwest
    north = resultados[ row ]['geometry']['viewport']['northeast']
    
     # Save results
    instituciones.append( institution )
    direccion.append( dire )
    actividad.append( act )
    northeast.append( north )
    southwest.append( south )

100%|██████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<?, ?it/s]


In [96]:
# Diccionario
resultado_final = { 'Institucion': instituciones, 'Direccion' : direccion, 'Estado' : actividad, 'Direccion_norte' : northeast, 'Direccion_sur' : southwest }
# Dataframe
dataframe = pd.DataFrame( resultado_final )
dataframe

Institucion  \
0             National Identity Management Commission   
1        National Identity Management Commission NIMC   
2      National Identity Management Commission (Nimc)   
3             National Identity Management Commission   
4      National Identity Management Commission (Nimc)   
5             National Identity Management Commission   
6             National Identity Management Commission   
7      National Identity Management Commission (Nimc)   
8      National Identity Management Commission (Nimc)   
9             National Identity Management Commission   
10     National Identity Management Commission (Nimc)   
11                National Identity Management Center   
12     National Identity Management Commission (Nimc)   
13  National Identity Management Commision (NIMC) ...   
14            National Identity Management Commission   
15  National Identity Management Commission, North...   
16     National Identity Management Commission (Nimc)   
17    National Identity Management Commission Umuahia   
18            National Identity Management Commission   
19       National Identity Management Commission Nimc   

                                            Direccion       Estado  \
0   11 Sokode Crescent, Off Dalaba Street Zone 5, ...  OPERATIONAL   
1                           Lafia - Shandam Rd, Lafia  OPERATIONAL   
2        Asa-Dam Rd, opp. Dangote Flour Mills, Ilorin  OPERATIONAL   
3                 zone 3, No 4 Maputo St, Wuse, Abuja  OPERATIONAL   
4                            Lamingo Dam Road Plateau  OPERATIONAL   
5                                                 Jos  OPERATIONAL   
6                                              Kachia  OPERATIONAL   
7                Jonah Jang Cres, High Level, Makurdi  OPERATIONAL   
8        3 Abdulkadir ahmed Close (P.M.B 0281, Bauchi  OPERATIONAL   
9                                  Kofar Kabuga, Kano  OPERATIONAL   
10         Complex, Federal Secretariat, Kawo, Kaduna  OPERATIONAL   
11                Port-Hacourt Rd, New Owerri, Owerri  OPERATIONAL   
12  ITF House, 6, 3rd Floor, Adetokunbo Ademola Cr...  OPERATIONAL   
13            9 Obafemi Awolowo Way, Agidingbi, Ikeja  OPERATIONAL   
14  1 Proda Road,Proda Junction, Emene industrial ...  OPERATIONAL   
15                 Bayajida Rd, Ungwan Munchi, Kaduna  OPERATIONAL   
16                         Tal-Udu, FCE Junction Kano  OPERATIONAL   
17                                Ndume bypass, Ndume  OPERATIONAL   
18                              Umueme, Port Harcourt  OPERATIONAL   
19  238 Port Harcourt - Aba Expy, Rumuokwurusi, Po...  OPERATIONAL   

                                      Direccion_norte  \
0   {'lat': 9.067332429892723, 'lng': 7.4562827798...   
1   {'lat': 8.506788579892724, 'lng': 8.5332722298...   
2   {'lat': 8.451072679892722, 'lng': 4.5437053298...   
3   {'lat': 9.06035997989272, 'lng': 7.46923637989...   
4                {'lat': 9.8984195, 'lng': 8.9328039}   
5   {'lat': 9.893702729892722, 'lng': 8.9188880798...   
6   {'lat': 9.858620379892722, 'lng': 7.9693469298...   
7   {'lat': 7.712382379892722, 'lng': 8.5282094298...   
8   {'lat': 10.31170367989272, 'lng': 9.8279278798...   
9   {'lat': 11.99139672989272, 'lng': 8.4903341298...   
10  {'lat': 10.59382137989272, 'lng': 7.4508104298...   
11  {'lat': 5.473014629892722, 'lng': 7.0094772798...   
12  {'lat': 9.078071879892722, 'lng': 7.4952152298...   
13  {'lat': 6.618298179892721, 'lng': 3.3595877798...   
14  {'lat': 6.461432879892723, 'lng': 7.5803212798...   
15  {'lat': 10.54495552989272, 'lng': 7.4623366798...   
16  {'lat': 11.98937482989272, 'lng': 8.4981432298...   
17  {'lat': 5.503745479892721, 'lng': 7.5191573798...   
18  {'lat': 4.823459929892723, 'lng': 7.0092882798...   
19  {'lat': 4.850934679892722, 'lng': 7.0540891798...   

                                        Direccion_sur  
0   {'lat': 9.064632770107277, 'lng': 7.4535831201...  
1   {'lat': 8.50408892010728, 'lng': 8.53057257010...  
2   {'l

## 3. Function:

- Crear una matrix aleatoria de orden 100x10. Crear un función que permita estandariza cada columna; es decir, cada observación de una columna debe restarse por su media y dividirse por la desviación estándar de la columna. Llame a esta función como standarize

In [100]:
# import module
import numpy as np
array = np.arange(1000) - 2  
matrix = array.reshape(100, 10)  
print("Matriz 10*100 \n", matrix)

Matriz 10*100 
 [[ -2  -1   0   1   2   3   4   5   6   7]
 [  8   9  10  11  12  13  14  15  16  17]
 [ 18  19  20  21  22  23  24  25  26  27]
 [ 28  29  30  31  32  33  34  35  36  37]
 [ 38  39  40  41  42  43  44  45  46  47]
 [ 48  49  50  51  52  53  54  55  56  57]
 [ 58  59  60  61  62  63  64  65  66  67]
 [ 68  69  70  71  72  73  74  75  76  77]
 [ 78  79  80  81  82  83  84  85  86  87]
 [ 88  89  90  91  92  93  94  95  96  97]
 [ 98  99 100 101 102 103 104 105 106 107]
 [108 109 110 111 112 113 114 115 116 117]
 [118 119 120 121 122 123 124 125 126 127]
 [128 129 130 131 132 133 134 135 136 137]
 [138 139 140 141 142 143 144 145 146 147]
 [148 149 150 151 152 153 154 155 156 157]
 [158 159 160 161 162 163 164 165 166 167]
 [168 169 170 171 172 173 174 175 176 177]
 [178 179 180 181 182 183 184 185 186 187]
 [188 189 190 191 192 193 194 195 196 197]
 [198 199 200 201 202 203 204 205 206 207]
 [208 209 210 211 212 213 214 215 216 217]
 [218 219 220 221 222 223 224 225 226 

In [106]:
def standarize(matrix):
    norm = np.linalg.norm(matrix, 1)
    # normalized matrix
    matrix = matrix/norm  
    return matrix
    standarize_matrix = standarize(matrix)
print("\nMatriz estandarizada \n", standarize_matrix)


Matriz estandarizada 
 [[-3.98406375e-05 -1.99203187e-05  0.00000000e+00  1.99203187e-05
   3.98406375e-05  5.97609562e-05  7.96812749e-05  9.96015936e-05
   1.19521912e-04  1.39442231e-04]
 [ 1.59362550e-04  1.79282869e-04  1.99203187e-04  2.19123506e-04
   2.39043825e-04  2.58964143e-04  2.78884462e-04  2.98804781e-04
   3.18725100e-04  3.38645418e-04]
 [ 3.58565737e-04  3.78486056e-04  3.98406375e-04  4.18326693e-04
   4.38247012e-04  4.58167331e-04  4.78087649e-04  4.98007968e-04
   5.17928287e-04  5.37848606e-04]
 [ 5.57768924e-04  5.77689243e-04  5.97609562e-04  6.17529880e-04
   6.37450199e-04  6.57370518e-04  6.77290837e-04  6.97211155e-04
   7.17131474e-04  7.37051793e-04]
 [ 7.56972112e-04  7.76892430e-04  7.96812749e-04  8.16733068e-04
   8.36653386e-04  8.56573705e-04  8.76494024e-04  8.96414343e-04
   9.16334661e-04  9.36254980e-04]
 [ 9.56175299e-04  9.76095618e-04  9.96015936e-04  1.01593625e-03
   1.03585657e-03  1.05577689e-03  1.07569721e-03  1.09561753e-03
   1.1155